# Discard eigenvalues with too many null values

In [5]:
import pandas as pd

## 1. Risk Level

In [2]:
file1 = 'fxsp.csv'
data1 = pd.read_csv(file1) #reading file
colname1 = data1.loc[0,:]

data1.drop([0],inplace = True)
data1.drop([1],inplace = True)
data1 = data1[data1["Typrep"] == "A"]

data1 = data1.fillna(1)

C:\Users\Ashley He\AppData\Local\Temp\ipykernel_19148\180219775.py:2: DtypeWarning: Columns (0,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv(file1) #reading file

In [106]:
data1[['Stkcd', 'Accper', 'Typrep', 'Indcd', 'F070101B', 'F070201B']]

         Stkcd      Accper Typrep Indcd  F070101B  F070201B
2       000001  2012-06-30      A   J66         1  1.065726
4       000001  2012-09-30      A   J66         1         1
6       000001  2012-12-31      A   J66         1  1.071584
8       000001  2013-03-31      A   J66         1         1
9       000001  2013-06-30      A   J66         1  1.069049
...        ...         ...    ...   ...       ...       ...
284760  900957  2021-09-30      A   K70  1.932653       1.0
284761  900957  2021-12-31      A   K70  1.947996  1.658589
284763  900957  2022-03-31      A   K70  1.732356       1.0
284764  900957  2022-06-30      A   K70  1.557705  1.530011
284766  900957  2022-09-30      A   K70  1.605945       1.0

[154083 rows x 6 columns]

In [3]:
data1.iloc[:,4:-1]

        F070101B  F070201B  F070301B
2              1  1.065726  1.065726
4              1         1         1
6              1  1.071584  1.071584
8              1         1         1
9              1  1.069049  1.069049
...          ...       ...       ...
284760  1.932653       1.0  1.932653
284761  1.947996  1.658589  3.230925
284763  1.732356       1.0  1.732356
284764  1.557705  1.530011  2.383306
284766  1.605945       1.0  1.605945

[154083 rows x 3 columns]

In [4]:
col1 = str(list(data1.columns))
index1 = colname1[data1.columns]

In [5]:
index1

Stkcd         股票代码
Accper      统计截止日期
Typrep      报表类型编码
Indcd         行业代码
F070101B      财务杠杆
F070201B      经营杠杆
F070301B      综合杠杆
Indnme        行业名称
Name: 0, dtype: object

In [6]:
with open('fxsp_index.txt', 'a+', encoding='utf-8') as f:
    f.write(col1 + "\n")
    for i in index1:
        f.write(i + '\n')
    f.close()

## 2. Stock Indicators

In [7]:
file2 = 'mgzb.csv'
data2 = pd.read_csv(file2)
colname2 = data2.loc[0,:]

data2.drop([0],inplace = True)
data2.drop([1],inplace = True)
data2 = data2[data2["Typrep"] == "A"]

for i in data2.columns:
    if data2[i].isnull().sum ()>5000:
        print("nan>5000:",i)
        data2 = data2.drop(i, axis = 1)

data2 = data2.fillna(0)

C:\Users\Ashley He\AppData\Local\Temp\ipykernel_19148\2210353809.py:2: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91) have mixed types. Specify dtype option on import or set low_memory=False.
  data2 = pd.read_csv(file2)

nan>5000: F090101C
nan>5000: F090102B
nan>5000: F090102C
nan>5000: F090103C
nan>5000: F090104B
nan>5000: F090104C
nan>5000: F090201C
nan>5000: F090202B
nan>5000: F090202C
nan>5000: F090301C
nan>5000: F090401C
nan>5000: F090501C
nan>5000: F090601C
nan>5000: F090701C
nan>5000: F090801C
nan>5000: F090901C
nan>5000: F091801C
nan>5000: F091901C
nan>5000: F092101C
nan>5000: F092201C
nan>5000: F092401B
nan>5000: F092501B
nan>5000: F092601C
nan>5000: F092602B
nan>5000: F092602C
nan>5000: F090302B
nan>5000: F090302C
nan>5000: F090402B
nan>5000: F090402C
nan>5000: F090502B
nan>5000: F090502C
nan>5000: F090602B
nan>5000: F090602C
nan>5000: F090702B
nan>5000: F090702C
nan>5000: F090802B
nan>5000: F090802C
nan>5000: F090902B
nan>5000: F090902C
nan>5000: F091002A
nan>5000: F091102A
nan>5000: F091202A
nan>5000: F091302A
nan>5000: F091402A
nan>5000: F091502A
nan>5000: F091602A
nan>5000: F091702A
nan>5000: F091802B
nan>5000: F091802C
nan>5000: F091902B
nan>5000: F091902C
nan>5000: F092002B
nan>5000: F092002C
nan>5000: F092102B
nan>5000: F092102C
nan>5000: F092202B
nan>5000: F092202C
nan>5000: F092302B
nan>5000: F092302C
nan>5000: F092103B
nan>5000: F092103C

In [8]:
col2 = str(list(data2.columns))
index2 = colname2[data2.columns]

In [9]:
index2

Stkcd                  股票代码
Accper               统计截止日期
Typrep               报表类型编码
Indcd                  行业代码
F090101B              每股收益1
F090103B              每股收益3
F090201B            每股综合收益1
F090301B         归属于母公司每股收益
F090401B       归属于母公司每股综合收益
F090501B            每股营业总收入
F090601B             每股营业收入
F090701B            息税前每股收益
F090801B        息税折旧摊销前每股收益
F090901B             每股营业利润
F091001A              每股净资产
F091101A             每股有形资产
F091201A               每股负债
F091301A             每股资本公积
F091401A             每股盈余公积
F091501A            每股未分配利润
F091601A             每股留存收益
F091701A        归属于母公司每股净资产
F091801B    每股经营活动产生的现金流量净额
F091901B        每股投资活动现金净流量
F092001B        每股筹资活动现金净流量
F092001C     每股筹资活动现金净流量TTM
F092101B         每股企业自由现金流量
F092201B         每股股东自由现金流量
F092301B            每股折旧和摊销
F092301C         每股折旧和摊销TTM
F092601B           每股现金净流量1
Indnme                 行业名称
Name: 0, dtype: object

In [10]:
with open('mgzb_index.txt', 'a+', encoding='utf-8') as f:
    f.write(col2 + "\n")
    for i in index2:
        f.write(i + '\n')
    f.close()

In [11]:
#data.to_csv("mgzb_select.csv")

## 3. Solvency

In [54]:
file3 = 'cznl.csv'
data3 = pd.read_csv(file3)
colname3 = data3.loc[0,:]

data3.drop([0],inplace = True)
data3.drop([1],inplace = True)
data3 = data3[data3["Typrep"] == "A"]

C:\Users\Ashley He\AppData\Local\Temp\ipykernel_12416\1768710843.py:2: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  data3 = pd.read_csv(file3)

### Financial Service J66

In [55]:
data3j66 = data3[data3["Indcd"] == "J66"]
for i in data3j66.columns:
    if data3j66[i].isnull().sum ()>200:
        print("nan>200:",i)
        data3j66 = data3j66.drop(i, axis = 1)

data3j66.fillna(0)

nan>200: F010101A
nan>200: F010201A
nan>200: F010301A
nan>200: F010401A
nan>200: F010501A
nan>200: F010601A
nan>200: F010701B
nan>200: F010702B
nan>200: F010801B
nan>200: F010901B
nan>200: F011001B
nan>200: F012101A
nan>200: F012201B
nan>200: F012401B
nan>200: F012701B

,Stkcd,Accper,Typrep,Indcd,F011201A,F011301A,F011401A,F011501A,F011601A,F011701A,F011801A,F011901A,F012001A,F012301B,F012501B,F012601B,F020502A,Indnme
2,000001,2010-03-31,A,J66,0.964335,0,0.964564,0,28.038557,27.038557,0.036984,0,0,0.014778,0.896348,27.219588,28.364366,货币金融服务
3,000001,2010-06-30,A,J66,0.951279,0,0.951524,0,20.525162,19.525162,0.051216,0,0,-0.005224,0.911475,19.628711,23.819849,货币金融服务
4,000001,2010-09-30,A,J66,0.952384,0,0.952616,0,21.001152,20.001152,0.049997,0,0,0.017483,0.922687,20.104246,24.002757,货币金融服务
5,000001,2010-12-31,A,J66,0.954349,0,0.954601,0,21.905454,20.905454,0.047834,0,0,0.034481,0.929486,21.026798,24.503225,货币金融服务
6,000001,2011-03-31,A,J66,0.955483,0,0.955707,0,22.463473,21.463473,0.046591,0,0,0.02913,0.934763,21.576884,22.19557,货币金融服务
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298425,603323,2021-09-30,A,J66,0.91419,0.0,0.915773,0.0,11.65367,10.65367,0.093864,0.0,0.0,-0.024871,0.932587,10.872692,11.57316,货币金融服务
298426,603323,2021-12-31,A,J66,0.916407,0.0,0.917969,0.0,11.96273,10.96273,0.091218,0.0,0.0,-0.013044,0.938747,11.190578,11.734876,货币金融服务
298428,603323,2022-03-31,A,J66,0.916797,0.0,0.918278,0.0,12.018802,11.018802,0.090754,0.0,0.0,0.005401,0.936612,11.236671,11.991154,货币金融服务
298429,603323,2022-06-30,A,J66,0.91894,0.0,0.920515,0.0,12.336573,11.336573,0.08821,0.0,0.0,0.020712,0.940355,11.580949,12.153336,货币金融服务
298431,603323,2022-09-30,A,J66,0.917593,0.0,0.919209,0.0,12.134838,11.134838,0.089808,0.0,0.0,0.016088,0.940867,11.377673,12.05265,货币金融服务

In [56]:
col3j66 = str(list(data3.columns))
index3j66 = colname3[data3.columns]

In [57]:
index3j66

Stkcd                     股票代码
Accper                  统计截止日期
Typrep                  报表类型编码
Indcd                     行业代码
F010101A                  流动比率
F010201A                  速动比率
F010301A                保守速动比率
F010401A                  现金比率
F010501A              营运资金与借款比
F010601A                  营运资金
F010701B               利息保障倍数A
F010702B               利息保障倍数B
F010801B    经营活动产生的现金流量净额／流动负债
F010901B             现金流利息保障倍数
F011001B           现金流到期债务保障倍数
F011201A                 资产负债率
F011301A             长期借款与总资产比
F011401A               有形资产负债率
F011501A             有形资产带息债务比
F011601A                  权益乘数
F011701A                  产权比率
F011801A               权益对负债比率
F011901A               长期资本负债率
F012001A              长期负债权益比率
F012101A           长期债务与营运资金比率
F012201B        息税折旧摊销前利润／负债合计
F012301B    经营活动产生的现金流量净额／负债合计
F012401B    经营活动产生的现金流量净额／带息债务
F012501B             负债与权益市价比率
F012601B               有形净值债务率
F012701B              固定支出偿付倍数
F020502A                 权益乘数2
Indnme                    行业名称
Name: 0, dtype: object

### Not Financial Service

In [58]:
data3else = data3[data3["Indcd"] != "J66"]
for i in data3else.columns:
    if data3else[i].isnull().sum ()> 2000:
        print("nan>2000:",i)
        data3else = data3else.drop(i, axis = 1)

data3else.fillna(0)

nan>2000: F010501A
nan>2000: F010701B
nan>2000: F010702B
nan>2000: F010901B
nan>2000: F011001B
nan>2000: F012201B
nan>2000: F012301B
nan>2000: F012401B
nan>2000: F012501B
nan>2000: F012601B
nan>2000: F012701B
nan>2000: F020502A

,Stkcd,Accper,Typrep,Indcd,F010101A,F010201A,F010301A,F010401A,F010601A,F010801B,...,F011301A,F011401A,F011501A,F011601A,F011701A,F011801A,F011901A,F012001A,F012101A,Indnme
68,000002,2010-03-31,A,K70,1.812404,0.480805,0.23573,0.22292,63152100042,-0.08748,...,0.1121,0.681002,0.242747,3.131145,2.131145,0.469231,0.329284,0.490945,0.368438,房地产业
70,000002,2010-06-30,A,K70,1.776353,0.477737,0.226439,0.209576,66676827441,-0.110781,...,0.122267,0.698696,0.246987,3.315021,2.315021,0.431962,0.351184,0.54127,0.393063,房地产业
72,000002,2010-09-30,A,K70,1.652441,0.518992,0.291984,0.282578,70914544334,-0.011108,...,0.124073,0.737797,0.243479,3.809237,2.809237,0.355969,0.377409,0.606192,0.42174,房地产业
74,000002,2010-12-31,A,K70,1.585187,0.556782,0.303978,0.270704,75869940703,0.017256,...,0.114964,0.748159,0.223838,3.950404,2.950404,0.338937,0.365179,0.575247,0.413874,房地产业
76,000002,2011-03-31,A,K70,1.479813,0.486104,0.252242,0.212343,72839206646,-0.013011,...,0.088362,0.762585,0.202996,4.193159,3.193159,0.31317,0.328207,0.488554,0.376475,房地产业
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332116,900957,2021-09-30,A,K70,3.23756,3.23756,3.14937,0.10862,204698117.4,0.084799,...,0.411464,0.502466,0.487083,1.998228,0.998228,1.001776,0.451212,0.822199,2.087464,房地产业
332117,900957,2021-12-31,A,K70,2.61501,2.61501,2.540741,0.006072,176782156.5,0.19702,...,0.378269,0.488567,0.474995,1.944507,0.944507,1.058753,0.424146,0.736552,2.193103,房地产业
332119,900957,2022-03-31,A,K70,2.686638,2.686638,2.611934,0.010447,188691080.1,-0.018986,...,0.374195,0.485751,0.469451,1.934202,0.934202,1.070432,0.420209,0.724759,2.051656,房地产业
332120,900957,2022-06-30,A,K70,2.903522,2.903522,2.886787,0.002531,208944502.8,0.044986,...,0.369852,0.478022,0.462494,1.906106,0.906106,1.103624,0.413813,0.705942,1.852785,房地产业
332122,900957,2022-09-30,A,K70,3.06085,3.06085,3.027571,0.014957,223593684.4,0.152363,...,0.367401,0.473618,0.458726,1.890403,0.890403,1.123087,0.410199,0.695487,1.731396,房地产业

In [59]:
col3else = str(list(data3.columns))
index3else = colname3[data3.columns]

In [60]:
index3else

Stkcd                     股票代码
Accper                  统计截止日期
Typrep                  报表类型编码
Indcd                     行业代码
F010101A                  流动比率
F010201A                  速动比率
F010301A                保守速动比率
F010401A                  现金比率
F010501A              营运资金与借款比
F010601A                  营运资金
F010701B               利息保障倍数A
F010702B               利息保障倍数B
F010801B    经营活动产生的现金流量净额／流动负债
F010901B             现金流利息保障倍数
F011001B           现金流到期债务保障倍数
F011201A                 资产负债率
F011301A             长期借款与总资产比
F011401A               有形资产负债率
F011501A             有形资产带息债务比
F011601A                  权益乘数
F011701A                  产权比率
F011801A               权益对负债比率
F011901A               长期资本负债率
F012001A              长期负债权益比率
F012101A           长期债务与营运资金比率
F012201B        息税折旧摊销前利润／负债合计
F012301B    经营活动产生的现金流量净额／负债合计
F012401B    经营活动产生的现金流量净额／带息债务
F012501B             负债与权益市价比率
F012601B               有形净值债务率
F012701B              固定支出偿付倍数
F020502A                 权益乘数2
Indnme                    行业名称
Name: 0, dtype: object

## 4. Development Capacity

In [19]:
file4 = 'fznl.csv'
data4 = pd.read_csv(file4)
colname4 = data4.loc[0,:]
data4.drop([0],inplace = True)
data4.drop([1],inplace = True)
data4 = data4[data4["Typrep"] == "A"]

C:\Users\Ashley He\AppData\Local\Temp\ipykernel_19148\4286018949.py:2: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60) have mixed types. Specify dtype option on import or set low_memory=False.
  data4 = pd.read_csv(file4)

### Financial Service J66

In [20]:
data4j66 = data4[data4["Indcd"] == "J66"]
for i in data4j66.columns:
    if data4j66[i].isnull().sum ()>200:
        print("nan>200:",i)
        data4j66 = data4j66.drop(i, axis = 1)

data4j66.fillna(0)

nan>200: F080901B
nan>200: F081501B
nan>200: F081901B
nan>200: F082001B
nan>200: F082101B
nan>200: F082201B
nan>200: F082202B
nan>200: F082301B
nan>200: F082302B
nan>200: F082401B
nan>200: F082402B
nan>200: F082501B
nan>200: F082502B

,Stkcd,Accper,Typrep,Indcd,F080101A,F080102A,F080201A,F080301A,F080302A,F080401A,...,F081003B,F081603B,F080603A,F081103B,F080503A,F080803B,F081203B,F082602B,F082603B,Indnme
2,000001,2010-03-31,A,J66,1.080129,1.295083,1.295083,0.080129,0.295083,0.295083,...,0.406426,0.122833,0.187875,0.316324,0.15469,0.416667,0.318119,0.076862,0.074126,货币金融服务
3,000001,2010-06-30,A,J66,1.48616,1.691246,1.691246,0.48616,0.691246,0.691246,...,0.31225,0.192762,0.153674,0.32165,0.284732,0.324324,0.302341,0.110746,0.119201,货币金融服务
4,000001,2010-09-30,A,J66,1.570335,1.683959,1.683959,0.570335,0.683959,0.683959,...,0.301456,0.218522,0.217945,0.324448,0.343526,0.247863,0.307758,0.172707,0.179951,货币金融服务
5,000001,2010-12-31,A,J66,1.621796,1.621796,1.621796,0.621796,0.621796,0.621796,...,0.249087,0.228627,0.237144,0.291975,0.395362,0.179012,0.274459,0.23348,0.234177,货币金融服务
6,000001,2011-03-31,A,J66,1.082914,1.625977,1.625977,0.082914,0.625977,0.625977,...,0.522192,0.419776,0.302674,0.536839,0.247684,0.352941,0.533697,0.071605,0.06948,货币金融服务
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298426,603323,2021-09-30,A,J66,1.084477,1.086767,1.086558,0.084477,0.086767,0.086558,...,0.181391,0.059678,0.147392,0.285412,0.033932,0.183673,0.300629,0.086236,0.082607,货币金融服务
298427,603323,2021-12-31,A,J66,1.092921,1.092921,1.093758,0.092921,0.092921,0.093758,...,0.211311,0.03861,0.138298,0.169671,0.126734,0.207547,0.176668,0.070426,0.068713,货币金融服务
298429,603323,2022-03-31,A,J66,1.028055,1.092581,1.093356,0.028055,0.092581,0.093356,...,0.214318,0.043969,0.147891,0.176351,0.065712,0.214286,0.183623,0.023327,0.02311,货币金融服务
298430,603323,2022-06-30,A,J66,1.040218,1.095558,1.096161,0.040218,0.095558,0.096161,...,0.212807,-0.007078,0.129613,0.266005,0.759701,0.205128,0.269537,0.065129,0.062352,货币金融服务
298432,603323,2022-09-30,A,J66,1.094077,1.102595,1.103769,0.094077,0.102595,0.103769,...,0.20192,-0.029628,0.14812,0.101307,0.754738,0.189655,0.086303,0.09474,0.090429,货币金融服务

In [21]:
col4j66 = str(list(data4.columns))
index4j66 = colname4[data4.columns]

In [22]:
index4j66

Stkcd             股票代码
Accper          统计截止日期
Typrep          报表类型编码
Indcd             行业代码
F080101A      资本保值增值率A
               ...
F080803B    基本每股收益增长率C
F081203B      营业利润增长率C
F082602B       可持续增长率2
F082603B       可持续增长率3
Indnme            行业名称
Name: 0, Length: 62, dtype: object

### Not Financial Service

In [23]:
data4else = data4[data4["Indcd"] != "J66"]
for i in data4else.columns:
    if data4else[i].isnull().sum ()> 20000:
        print("nan>20000:",i)
        data4else = data4else.drop(i, axis = 1)

data4else.fillna(0)

nan>20000: F080701B
nan>20000: F080702B
nan>20000: F080801B
nan>20000: F080802B
nan>20000: F080901B
nan>20000: F080902B
nan>20000: F081001B
nan>20000: F081002B
nan>20000: F081101B
nan>20000: F081102B
nan>20000: F081201B
nan>20000: F081202B
nan>20000: F081301B
nan>20000: F081401B
nan>20000: F081501B
nan>20000: F082201B
nan>20000: F082202B
nan>20000: F082301B
nan>20000: F082302B
nan>20000: F082401B
nan>20000: F082402B
nan>20000: F082501B
nan>20000: F082502B
nan>20000: F082603B

,Stkcd,Accper,Typrep,Indcd,F080101A,F080102A,F080201A,F080301A,F080302A,F080401A,...,F080703B,F081003B,F081603B,F080603A,F081103B,F080503A,F080803B,F081203B,F082602B,Indnme
68,000002,2010-03-31,A,K70,1.043714,1.192819,1.192354,0.043714,0.192819,0.192354,...,0.109527,0.323465,-0.08076,0.188747,0.263854,0.090678,0.428571,0.251995,0.025444,房地产业
70,000002,2010-06-30,A,K70,1.066316,1.158232,1.152129,0.066316,0.158232,0.152129,...,-0.11974,0.019545,-0.231207,0.289052,-0.010228,0.146402,0.130435,-0.017309,0.069839,房地产业
72,000002,2010-09-30,A,K70,1.086508,1.164587,1.152033,0.086508,0.164587,0.152033,...,-0.104905,0.042415,-0.242467,0.45121,0.009102,0.152612,0.107807,-0.002906,0.08406,房地产业
74,000002,2010-12-31,A,K70,1.202114,1.202114,1.183455,0.202114,0.202114,0.183455,...,0.143605,0.374743,0.037496,0.567036,0.385652,-0.100588,0.375,0.369577,0.165224,房地产业
76,000002,2011-03-31,A,K70,1.028268,1.184323,1.168132,0.028268,0.184323,0.168132,...,-0.145577,0.011913,0.061997,0.586019,0.079172,-0.099061,0.1,0.069354,0.02166,房地产业
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332113,900957,2021-09-30,A,K70,1.04206,1.052685,1.052742,0.04206,0.052685,0.052742,...,0.184345,0.246741,0.081078,0.020568,0.244195,-0.077533,0.24948,0.305734,0.04206,房地产业
332114,900957,2021-12-31,A,K70,1.055433,1.055433,1.055558,0.055433,0.055433,0.055558,...,0.198323,0.264749,0.137471,0.014848,0.310943,-0.077713,0.2688,0.371571,0.055433,房地产业
332116,900957,2022-03-31,A,K70,1.014772,1.053354,1.053491,0.014772,0.053354,0.053491,...,-0.117625,-0.070547,0.050921,0.014176,0.006919,-0.079044,-0.083333,0.006919,0.014772,房地产业
332117,900957,2022-06-30,A,K70,1.041821,1.067646,1.067863,0.041821,0.067646,0.067863,...,0.38254,0.476063,0.153919,0.034448,0.512438,-0.080696,0.480094,0.512504,0.041821,房地产业
332119,900957,2022-09-30,A,K70,1.057481,1.071052,1.071273,0.057481,0.071052,0.071273,...,0.346733,0.442422,0.098328,0.013258,0.452553,-0.08229,0.44426,0.45326,0.057481,房地产业

In [24]:
col4else = str(list(data4else.columns))
index4else = colname4[data4else.columns]

In [25]:
index4else

Stkcd             股票代码
Accper          统计截止日期
Typrep          报表类型编码
Indcd             行业代码
F080101A      资本保值增值率A
F080102A      资本保值增值率B
F080201A    母公司资本保值增值率
F080301A        资本积累率A
F080302A        资本积累率B
F080401A      母公司资本积累率
F080501A      固定资产增长率A
F080502A      固定资产增长率B
F080601A       总资产增长率A
F080602A       总资产增长率B
F081601B      营业收入增长率A
F081602C      营业收入增长率B
F081701B      营业总收入增长率
F081801B      营业总成本增长率
F081901B       销售费用增长率
F082001B       管理费用增长率
F082101B          应计项目
F082601B        可持续增长率
F082701A     所有者权益增长率A
F082702A     所有者权益增长率B
F082801A     每股净资产增长率B
F082802A     每股净资产增长率A
F082703A     所有者权益增长率C
F082803A     每股净资产增长率C
F080703B    净资产收益率增长率C
F081003B       净利润增长率C
F081603B      营业收入增长率C
F080603A       总资产增长率C
F081103B      利润总额增长率C
F080503A      固定资产增长率C
F080803B    基本每股收益增长率C
F081203B      营业利润增长率C
F082602B       可持续增长率2
Indnme            行业名称
Name: 0, dtype: object

## 5. Operating Capacity

In [26]:
file5 = 'jynl.csv'
data5 = pd.read_csv(file5)
colname5 = data5.loc[0,:]

data5.drop([0],inplace = True)
data5.drop([1],inplace = True)
data5 = data5[data5["Typrep"] == "A"]

C:\Users\Ashley He\AppData\Local\Temp\ipykernel_19148\359730691.py:2: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  data5 = pd.read_csv(file5)

### Financial Service J66

In [27]:
data5j66 = data5[data5["Indcd"] == "J66"]
for i in data5j66.columns:
    if data5j66[i].isnull().sum ()>200:
        print("nan>200:",i)
        data5j66 = data5j66.drop(i, axis = 1)

data5j66.fillna(0)

nan>200: F040201B
nan>200: F040202B
nan>200: F040203B
nan>200: F040204B
nan>200: F040205C
nan>200: F040301B
nan>200: F040302B
nan>200: F040303B
nan>200: F040304C
nan>200: F040501B
nan>200: F040502B
nan>200: F040503B
nan>200: F040504B
nan>200: F040505C
nan>200: F040601B
nan>200: F040602B
nan>200: F040603B
nan>200: F040604C
nan>200: F040701B
nan>200: F040702B
nan>200: F040703B
nan>200: F040704C
nan>200: F040801B
nan>200: F040802B
nan>200: F040803B
nan>200: F040804B
nan>200: F040805C
nan>200: F040901B
nan>200: F040902B
nan>200: F040903B
nan>200: F040904B
nan>200: F040905C
nan>200: F041101B
nan>200: F041201B
nan>200: F041202B
nan>200: F041203B
nan>200: F041204B
nan>200: F041205C
nan>200: F041501B
nan>200: F041502B
nan>200: F041503B
nan>200: F041504B
nan>200: F041505C

,Stkcd,Accper,Typrep,Indcd,F040101B,F040401B,F041001B,F041002B,F041003B,F041004B,...,F041702B,F041703B,F041704B,F041705C,F041801B,F041802B,F041803B,F041804B,F041805C,Indnme
2,000001,2010-03-31,A,J66,9.603944,0,0.070413,0.084857,0.071359,0.285435,...,0.006552,0.006552,0.026209,0.025795,0.178956,0.18585,0.18585,0.743399,0.751709,货币金融服务
3,000001,2010-06-30,A,J66,4.550498,0,0.146218,0.164505,0.148325,0.296651,...,0.013583,0.013583,0.027165,0.026809,0.270619,0.323538,0.323538,0.647076,0.64552,货币金融服务
4,000001,2010-09-30,A,J66,2.359143,0,0.197929,0.235161,0.213794,0.285059,...,0.020136,0.020136,0.026848,0.026964,0.395545,0.483312,0.483312,0.644417,0.64701,货币金融服务
5,000001,2010-12-31,A,J66,1.835202,0,0.257702,0.285904,0.285904,0.285904,...,0.02671,0.02671,0.02671,0.02671,0.52901,0.654472,0.654472,0.654472,0.654472,货币金融服务
6,000001,2011-03-31,A,J66,6.577245,0,0.069064,0.081692,0.075158,0.300633,...,0.00732,0.00732,0.029282,0.026932,0.156262,0.162482,0.162482,0.649927,0.66217,货币金融服务
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291621,603323,2021-09-30,A,J66,0.0,0.0,0.563093,0.598782,0.491325,0.6551,...,0.017273,0.017273,0.023031,0.022832,0.192119,0.199905,0.199905,0.26654,0.25934,货币金融服务
291622,603323,2021-12-31,A,J66,0.0,0.0,0.795472,0.658036,0.658036,0.658036,...,0.021845,0.021845,0.021845,0.021845,0.245452,0.25635,0.25635,0.25635,0.25635,货币金融服务
291624,603323,2022-03-31,A,J66,0.0,0.0,0.236126,0.207112,0.221285,0.885139,...,0.005283,0.005283,0.021133,0.021467,0.062489,0.063354,0.063354,0.253414,0.252065,货币金融服务
291625,603323,2022-06-30,A,J66,0.0,0.0,0.374211,0.392179,0.388524,0.777047,...,0.010054,0.010054,0.020109,0.020218,0.119832,0.122194,0.122194,0.244388,0.245829,货币金融服务
291627,603323,2022-09-30,A,J66,0.0,0.0,0.546229,0.54632,0.571632,0.762176,...,0.014659,0.014659,0.019545,0.019308,0.16908,0.176676,0.176676,0.235568,0.229879,货币金融服务

In [28]:
col5j66 = str(list(data5j66.columns))
index5j66 = colname5[data5j66.columns]

In [29]:
index5j66 #少

Stkcd                 股票代码
Accper              统计截止日期
Typrep              报表类型编码
Indcd                 行业代码
F040101B          应收账款与收入比
F040401B            存货与收入比
F041001B      现金及现金等价物周转率A
F041002B      现金及现金等价物周转率B
F041003B      现金及现金等价物周转率C
F041004B      现金及现金等价物周转率D
F041005C    现金及现金等价物周转率TTM
F041301B          固定资产与收入比
F041401B          固定资产周转率A
F041402B          固定资产周转率B
F041403B          固定资产周转率C
F041404B          固定资产周转率D
F041405C        固定资产周转率TTM
F041601B             资本密集度
F041701B           总资产周转率A
F041702B           总资产周转率B
F041703B           总资产周转率C
F041704B           总资产周转率D
F041705C         总资产周转率TTM
F041801B          股东权益周转率A
F041802B          股东权益周转率B
F041803B          股东权益周转率C
F041804B          股东权益周转率D
F041805C        股东权益周转率TTM
Indnme                行业名称
Name: 0, dtype: object

### Not Financial Service

In [30]:
data5else = data5[data5["Indcd"] != "J66"]
for i in data5else.columns:
    if data5else[i].isnull().sum ()> 10000:
        print("nan>10000:",i)
        data5else = data5else.drop(i, axis = 1)

data5else.fillna(0)

nan>10000: F040205C
nan>10000: F040304C
nan>10000: F040505C
nan>10000: F040604C
nan>10000: F040704C
nan>10000: F040801B
nan>10000: F040802B
nan>10000: F040805C
nan>10000: F040901B
nan>10000: F040902B
nan>10000: F040903B
nan>10000: F040904B
nan>10000: F040905C
nan>10000: F041002B
nan>10000: F041005C
nan>10000: F041202B
nan>10000: F041205C
nan>10000: F041402B
nan>10000: F041405C
nan>10000: F041502B
nan>10000: F041505C
nan>10000: F041702B
nan>10000: F041705C
nan>10000: F041802B
nan>10000: F041805C

,Stkcd,Accper,Typrep,Indcd,F040101B,F040201B,F040202B,F040203B,F040204B,F040301B,...,F041503B,F041504B,F041601B,F041701B,F041703B,F041704B,F041801B,F041803B,F041804B,Indnme
68,000002,2010-03-31,A,K70,0.054202,18.449607,13.402043,13.402043,53.608172,4.878153,...,1.014576,4.058306,19.773025,0.050574,0.052481,0.209926,0.158354,0.161742,0.646966,房地产业
70,000002,2010-06-30,A,K70,0.020057,49.857277,31.951739,31.951739,63.903478,3.630363,...,2.200822,4.401644,9.573512,0.104455,0.11248,0.22496,0.34627,0.357383,0.714766,房地产业
72,000002,2010-09-30,A,K70,0.008603,116.239524,49.4197,49.4197,65.892933,2.348599,...,2.866532,3.822043,8.397305,0.119086,0.137496,0.183328,0.453626,0.472434,0.629912,房地产业
74,000002,2010-12-31,A,K70,0.031432,31.814975,43.961069,43.961069,43.961069,11.472585,...,5.828477,5.828477,4.252044,0.235181,0.28713,0.28713,0.92906,1.014331,1.014331,房地产业
76,000002,2011-03-31,A,K70,0.138371,7.226949,5.910731,5.910731,23.642922,12.453388,...,0.765303,3.061214,29.529647,0.033864,0.035345,0.14138,0.141998,0.143977,0.575909,房地产业
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326408,900957,2021-09-30,A,K70,3.041312,0.328805,0.366634,0.366634,0.488845,830.279345,...,0.114429,0.152572,12.068359,0.082861,0.084073,0.112097,0.165576,0.168986,0.225315,房地产业
326409,900957,2021-12-31,A,K70,2.351611,0.42524,0.477495,0.477495,0.477495,858.33882,...,0.150864,0.150864,9.052161,0.110471,0.111285,0.111285,0.214811,0.220605,0.220605,房地产业
326411,900957,2022-03-31,A,K70,9.81436,0.101892,0.10589,0.10589,0.423561,883.288187,...,0.039876,0.159503,35.253699,0.028366,0.028498,0.113994,0.054865,0.055268,0.22107,房地产业
326412,900957,2022-06-30,A,K70,4.835859,0.206789,0.223558,0.223558,0.447115,875.288337,...,0.088382,0.176764,16.158448,0.061887,0.062538,0.125075,0.117963,0.12038,0.240759,房地产业
326414,900957,2022-09-30,A,K70,3.380637,0.295802,0.322891,0.322891,0.430521,922.914652,...,0.129694,0.172925,11.133623,0.089818,0.091061,0.121414,0.169792,0.174536,0.232715,房地产业

In [31]:
col5else = str(list(data5else.columns))
index5else = colname5[data5else.columns]

In [32]:
index5else

Stkcd               股票代码
Accper            统计截止日期
Typrep            报表类型编码
Indcd               行业代码
F040101B        应收账款与收入比
F040201B        应收账款周转率A
F040202B        应收账款周转率B
F040203B        应收账款周转率C
F040204B        应收账款周转率D
F040301B       应收账款周转天数A
F040302B       应收账款周转天数B
F040303B       应收账款周转天数C
F040401B          存货与收入比
F040501B          存货周转率A
F040502B          存货周转率B
F040503B          存货周转率C
F040504B          存货周转率D
F040601B         存货周转天数A
F040602B         存货周转天数B
F040603B         存货周转天数C
F040701B           营业周期A
F040702B           营业周期B
F040703B           营业周期C
F040803B        应付账款周转率C
F040804B     应付账款周转率D(%)
F041001B    现金及现金等价物周转率A
F041003B    现金及现金等价物周转率C
F041004B    现金及现金等价物周转率D
F041101B        流动资产与收入比
F041201B        流动资产周转率A
F041203B        流动资产周转率C
F041204B        流动资产周转率D
F041301B        固定资产与收入比
F041401B        固定资产周转率A
F041403B        固定资产周转率C
F041404B        固定资产周转率D
F041501B       非流动资产周转率A
F041503B       非流动资产周转率C
F041504B       非流动资产周转率D
F041601B           资本密集度
F041701B         总资产周转率A
F041703B         总资产周转率C
F041704B         总资产周转率D
F041801B        股东权益周转率A
F041803B        股东权益周转率C
F041804B        股东权益周转率D
Indnme              行业名称
Name: 0, dtype: object

## 6. Cash Flow Analysis

In [6]:
file6 = 'xjlfx.csv'
data6 = pd.read_csv(file6)
colname6 = data6.loc[0,:]

data6.drop([0],inplace = True)
data6.drop([1],inplace = True)
data6 = data6[data6["Typrep"] == "A"]

C:\Users\Ashley He\AppData\Local\Temp\ipykernel_12416\2308759722.py:2: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  data6 = pd.read_csv(file6)

### Financial Service J66

In [7]:
data6j66 = data6[data6["Indcd"] == "J66"]
for i in data6j66.columns:
    if data6j66[i].isnull().sum ()>100:
        print("nan>100:",i)
        data6j66 = data6j66.drop(i, axis = 1)

data6j66.fillna(0)

nan>100: F060201B
nan>100: F060201C
nan>100: F061201B
nan>100: F061201C
nan>100: F061301B
nan>100: F061301C
nan>100: F061401B
nan>100: F061401C
nan>100: F061501B
nan>100: F061601B
nan>100: F061901B
nan>100: F062101B
nan>100: F062301B
nan>100: F062401B

,Stkcd,Accper,Typrep,Indcd,F060101B,F060101C,F060301B,F060301C,F060401B,F060401C,...,F061001C,F061302B,F061302C,F061402B,F061402C,F061701B,F061801B,F062001B,F062201B,Indnme
2,000001,2010-03-31,A,J66,5.455636,6.943404,2.17597,2.586923,4.315281,5.736923,...,-579394000,1858771000,18218644000,1858771000,19708835000,0.013888,5.736412,18.160879,25.552068,货币金融服务
3,000001,2010-06-30,A,J66,-1.000105,4.400779,-0.368469,1.62025,-0.79726,3.594685,...,6467568000,-4871832000,6132930000,-5331532000,6049882000,-0.004858,-1.065799,-11.135642,23.588485,货币金融服务
4,000001,2010-09-30,A,J66,2.234881,7.022928,0.832108,2.596311,1.787278,5.697859,...,6357685000,3114408000,14006565000,3091041000,13983026000,0.015672,2.439711,10.039592,22.409318,货币金融服务
5,000001,2010-12-31,A,J66,3.460683,3.460683,1.23827,1.23827,2.770386,2.770386,...,6382268000,7085759000,7085759000,7062057000,7062057000,0.029904,3.587739,15.681335,23.247679,货币金融服务
6,000001,2011-03-31,A,J66,8.886254,4.851394,3.799932,1.793874,6.976095,3.868276,...,6752293000,13564519000,18791507000,13191969000,18395255000,0.026433,9.444356,695.939426,27.787583,货币金融服务
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298392,603323,2021-09-30,A,J66,-3.183296,-4.533044,-1.315436,-1.547811,-2.571938,-3.711814,...,-375100000.0,-2722111000.0,-3220000000.0,-857135000.0,910556000.0,-0.021686,-4.331821,-5.455454,3.882618,货币金融服务
298393,603323,2021-12-31,A,J66,-1.531668,-1.531668,-0.546235,-0.546235,-1.415671,-1.415671,...,-549409000.0,-4527579000.0,-4527579000.0,-1160751000.0,-1160751000.0,-0.011208,-2.612959,-2.288604,4.219809,货币金融服务
298395,603323,2022-03-31,A,J66,2.568633,-1.260812,0.937,-0.465752,2.314077,-1.170513,...,-585133000.0,-1084444000.0,-3386478000.0,-428303000.0,-426253000.0,0.004872,3.918013,5.268323,5.300356,货币金融服务
298396,603323,2022-06-30,A,J66,3.70488,3.783467,1.890479,1.526849,3.105815,3.369644,...,-538684000.0,1052285000.0,2066253000.0,720972000.0,943675000.0,0.018363,6.574568,6.158301,5.459111,货币金融服务
298398,603323,2022-09-30,A,J66,1.966319,2.927927,1.006431,1.262986,1.75777,2.936994,...,-589387000.0,300370000.0,-1505098000.0,894490000.0,590874000.0,0.014023,3.407565,3.79127,4.965086,货币金融服务

In [8]:
col6j66 = str(list(data6j66.columns))
index6j66 = colname6[data6j66.columns]

In [9]:
index6j66

Stkcd                  股票代码
Accper               统计截止日期
Typrep               报表类型编码
Indcd                  行业代码
F060101B           净利润现金净含量
F060101C        净利润现金净含量TTM
F060301B          营业收入现金净含量
F060301C       营业收入现金净含量TTM
F060401B          营业利润现金净含量
F060401C       营业利润现金净含量TTM
F060901B       筹资活动债权人现金净流量
F060901C    筹资活动债权人现金净流量TTM
F061001B        筹资活动股东现金净流量
F061001C     筹资活动股东现金净流量TTM
F061302B             公司现金流2
F061302C          公司现金流TTM2
F061402B             股权现金流2
F061402C          股权现金流TTM2
F061701B            全部现金回收率
F061801B               营运指数
F062001B             现金适合比率
F062201B           现金满足投资比率
Indnme                 行业名称
Name: 0, dtype: object

### Not Financial Service

In [10]:
data6else = data6[data6["Indcd"] != "J66"]
for i in data6else.columns:
    if data6else[i].isnull().sum ()> 10000:
        print("nan>10000:",i)
        data6else = data6else.drop(i, axis = 1)

data6else.fillna(0)

nan>10000: F060101B
nan>10000: F060101C
nan>10000: F060201C
nan>10000: F060401B
nan>10000: F060401C
nan>10000: F061201B
nan>10000: F061201C
nan>10000: F061301C
nan>10000: F061401C
nan>10000: F061901B
nan>10000: F062301B
nan>10000: F062401B

,Stkcd,Accper,Typrep,Indcd,F060201B,F060301B,F060301C,F060901B,F060901C,F061001B,...,F061402B,F061402C,F061501B,F061601B,F061701B,F061801B,F062001B,F062101B,F062201B,Indnme
68,000002,2010-03-31,A,K70,1.651162,-0.906096,-0.025539,3334371539,-1420582067,209150474.2,...,-4883255996,-8289309459,-3174639624,-5148272435,-0.045825,-6.184768,-0.485024,-0.09967,-0.11066,房地产业
70,000002,2010-06-30,A,K70,1.721934,-0.567472,-0.229994,6843445646,7277817085,-751258796.5,...,-3252132825,-7743426472,-7086725049,-12353741496,-0.059275,-3.663863,-0.407069,-0.131558,-0.126046,房地产业
72,000002,2010-09-30,A,K70,2.425488,-0.053947,-0.076592,12991662156,13038506373,-1458901949,...,10169814539,4300095089,-16132117291,-25239450165,-0.006424,-0.369132,-0.033334,-0.015704,-0.044676,房地产业
74,000002,2010-12-31,A,K70,1.737586,0.044115,0.044115,15084715899,15084715899,-2060186137,...,15154346615,15154346615,-17320596438,-29679245455,0.010375,0.289648,0.047051,0.027423,-0.015042,房地产业
76,000002,2011-03-31,A,K70,3.126984,-0.247823,0.137991,-616909273.2,11133435087,-158509584.4,...,-2703159570,17334443041,5102175999,-373882364.9,-0.008392,-1.67576,-0.107052,-0.025005,-0.007111,房地产业
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332081,900957,2021-09-30,A,K70,0.401139,0.090153,0.137509,4513186.35,-4486813.65,-18861550.66,...,13176614.96,-6128590.25,14530605.42,-25473863.06,0.00747,0,0.408982,0.008407,2.08416,房地产业
332082,900957,2021-12-31,A,K70,0.516225,0.190731,0.190731,-17753499.17,-17753499.17,-25112140.3,...,10155039.43,10155039.43,123260564.8,26011689.39,0.02107,0,0.80152,0.024269,2.065066,房地产业
332084,900957,2022-03-31,A,K70,0.252693,-0.072476,0.182252,-324514.38,-324514.38,-6084823.03,...,6588912.97,1414941.97,7970768.065,1951642.55,-0.002056,0,-0.342083,-0.002368,1.352885,房地产业
332085,900957,2022-06-30,A,K70,0.322514,0.076334,0.224237,-1853966.04,-56820651.56,-12114251.47,...,11727440.39,22594589.66,35429945.45,21752812.53,0.004724,0,0.401562,0.00542,1.343438,房地产业
332087,900957,2022-09-30,A,K70,0.494791,0.174908,0.24964,-2578534.52,-24845220.04,-17938997.07,...,18897063.24,15875487.71,22296636.06,-22937269.8,0.01571,0,0.906176,0.017963,1.37112,房地产业

In [11]:
col6else = str(list(data6else.columns))
index6else = colname6[data6else.columns]

In [12]:
index6else

Stkcd                  股票代码
Accper               统计截止日期
Typrep               报表类型编码
Indcd                  行业代码
F060201B           营业收入现金含量
F060301B          营业收入现金净含量
F060301C       营业收入现金净含量TTM
F060901B       筹资活动债权人现金净流量
F060901C    筹资活动债权人现金净流量TTM
F061001B        筹资活动股东现金净流量
F061001C     筹资活动股东现金净流量TTM
F061301B             公司现金流1
F061302B             公司现金流2
F061302C          公司现金流TTM2
F061401B             股权现金流1
F061402B             股权现金流2
F061402C          股权现金流TTM2
F061501B        公司自由现金流(原有)
F061601B        股权自由现金流(原有)
F061701B            全部现金回收率
F061801B               营运指数
F062001B             现金适合比率
F062101B            现金再投资比率
F062201B           现金满足投资比率
Indnme                 行业名称
Name: 0, dtype: object

## 7. Profitability

In [36]:
file7 = 'ylnl.csv'
data7 = pd.read_csv(file7)
colname7 = data7.loc[0,:]

data7.drop([0],inplace = True)
data7.drop([1],inplace = True)
data7 = data7[data7["Typrep"] == "A"]

C:\Users\Ashley He\AppData\Local\Temp\ipykernel_12416\467041974.py:2: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71) have mixed types. Specify dtype option on import or set low_memory=False.
  data7 = pd.read_csv(file7)

### Financial Service J66

In [37]:
data7j66 = data7[data7["Indcd"] == "J66"]
for i in data7j66.columns:
    if data7j66[i].isnull().sum ()>200:
        print("nan>200:",i)
        data7j66 = data7j66.drop(i, axis = 1)

data7j66 = data7j66.fillna(0)

nan>200: F050301B
nan>200: F050302B
nan>200: F050303B
nan>200: F050304C
nan>200: F050601B
nan>200: F050601C
nan>200: F050701B
nan>200: F050801B
nan>200: F050801C
nan>200: F051001B
nan>200: F051101B
nan>200: F051201B
nan>200: F053201B
nan>200: F053301B
nan>200: F053301C
nan>200: F051301B
nan>200: F051301C
nan>200: F051801B
nan>200: F051801C
nan>200: F051901B
nan>200: F051901C
nan>200: F052001B
nan>200: F052001C
nan>200: F052101B
nan>200: F052101C
nan>200: F052301B
nan>200: F052301C
nan>200: F052401B
nan>200: F052401C
nan>200: F053102B
nan>200: F053104C
nan>200: F053401B

In [38]:
col7j66 = str(list(data7j66.columns))
index7j66 = colname7[data7j66.columns]

In [39]:
index7j66

Stkcd                       股票代码
Accper                    统计截止日期
Typrep                    报表类型编码
Indcd                       行业代码
F050101B                  资产报酬率A
F050102B                  资产报酬率B
F050103B                  资产报酬率C
F050104C                资产报酬率TTM
F050201B           总资产净利润率(ROA)A
F050202B           总资产净利润率(ROA)B
F050203B           总资产净利润率(ROA)C
F050204C         总资产净利润率(ROA)TTM
F050401B               固定资产净利润率A
F050402B               固定资产净利润率B
F050403B               固定资产净利润率C
F050404C             固定资产净利润率TTM
F050501B            净资产收益率（ROE）A
F050502B            净资产收益率（ROE）B
F050503B            净资产收益率（ROE）C
F050504C          净资产收益率（ROE）TTM
F050901B               净利润与利润总额比
F051401B                   营业利润率
F051401C                营业利润率TTM
F051501B                   营业净利率
F051501C                营业净利率TTM
F051601B                  总营业成本率
F051601C               总营业成本率TTM
F051701B                   销售费用率
F051701C                销售费用率TTM
F052201B             资产减值损失／营业收入
F052201C          资产减值损失／营业收入TTM
F052901B                现金与利润总额比
F052901C             现金与利润总额比TTM
F053001B      归属于母公司净资产收益率（ROE）A
F053002B      归属于母公司净资产收益率（ROE）B
F053003B      归属于母公司净资产收益率（ROE）C
F053004C    归属于母公司净资产收益率（ROE）TTM
F053101B            归属于母公司综合收益率A
F053103B            归属于母公司综合收益率C
F053202B                   投资收益率
Indnme                      行业名称
Name: 0, dtype: object

### Not Financial Service

In [40]:
data7else = data7[data7["Indcd"] != "J66"]
for i in data7else.columns:
    if data7else[i].isnull().sum ()> 10000:
        print("nan>10000:",i)
        data7else = data7else.drop(i, axis = 1)

data7else.fillna(0)

nan>10000: F050102B
nan>10000: F050104C
nan>10000: F050202B
nan>10000: F050204C
nan>10000: F050302B
nan>10000: F050304C
nan>10000: F050402B
nan>10000: F050404C
nan>10000: F050502B
nan>10000: F050504C
nan>10000: F050601C
nan>10000: F050801C
nan>10000: F050901B
nan>10000: F051001B
nan>10000: F053201B
nan>10000: F053301C
nan>10000: F051301C
nan>10000: F051401C
nan>10000: F051501C
nan>10000: F051601C
nan>10000: F051701C
nan>10000: F051801C
nan>10000: F051901C
nan>10000: F052001C
nan>10000: F052101C
nan>10000: F052201C
nan>10000: F052301C
nan>10000: F052401C
nan>10000: F052901B
nan>10000: F052901C
nan>10000: F053002B
nan>10000: F053004C
nan>10000: F053102B
nan>10000: F053104C
nan>10000: F053202B
nan>10000: F053401B

,Stkcd,Accper,Typrep,Indcd,F050101B,F050103B,F050201B,F050203B,F050301B,F050303B,...,F052001B,F052101B,F052201B,F052301B,F052401B,F053001B,F053003B,F053101B,F053103B,Indnme
68,000002,2010-03-31,A,K70,0.011167,0.011589,0.007924,0.008223,0.008347,0.008672,...,0.094356,0.250149,-0.023045,0.220814,0.220814,0.028902,0.029509,0.029107,0.029718,房地产业
70,000002,2010-06-30,A,K70,0.027471,0.029582,0.019692,0.021205,0.020718,0.022347,...,0.085349,0.310279,-0.013845,0.266415,0.262995,0.070714,0.072911,0.069552,0.071713,房地产业
72,000002,2010-09-30,A,K70,0.02852,0.032929,0.020356,0.023503,0.0213,0.024687,...,0.096967,0.27983,-0.009816,0.23949,0.23949,0.081281,0.084296,0.080699,0.083692,房地产业
74,000002,2010-12-31,A,K70,0.057712,0.070461,0.040993,0.050048,0.043011,0.052641,...,0.087347,0.297572,-0.010755,0.247289,0.245396,0.164655,0.178489,0.164804,0.17865,房地产业
76,000002,2011-03-31,A,K70,0.007749,0.008087,0.005056,0.005277,0.005297,0.005533,...,0.138696,0.267128,0.004857,0.228813,0.228813,0.026467,0.026851,0.027352,0.027748,房地产业
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335061,900957,2021-09-30,A,K70,0.041654,0.042263,0.020199,0.020494,0.070823,0.077253,...,0.298083,0.340684,0.0,0.502692,0.502692,0.04042,0.041254,0.04042,0.041254,房地产业
335062,900957,2021-12-31,A,K70,0.05783,0.058257,0.02701,0.027209,0.096581,0.103713,...,0.317993,0.353257,0.0,0.868255,0.52349,0.052634,0.054057,0.052634,0.054057,房地产业
335064,900957,2022-03-31,A,K70,0.014125,0.014191,0.007526,0.007561,0.02587,0.026502,...,0.261698,0.393692,0.0,0.49795,0.49795,0.014581,0.014688,0.014581,0.014688,房地产业
335065,900957,2022-06-30,A,K70,0.034897,0.035264,0.02106,0.021281,0.069071,0.072778,...,0.239495,0.554042,0.0,0.862742,0.563879,0.040262,0.041089,0.040262,0.041089,房地产业
335067,900957,2022-09-30,A,K70,0.049618,0.050305,0.028754,0.029152,0.09111,0.097865,...,0.251325,0.508394,0.0,0.552432,0.552432,0.054496,0.056023,0.054496,0.056023,房地产业

In [41]:
data7else.isnull().sum ()

Stkcd          0
Accper         0
Typrep         0
Indcd        133
F050101B    1543
F050103B    4196
F050201B    1543
F050203B    4196
F050301B    3350
F050303B    5973
F050401B    1658
F050403B    4287
F050501B    3069
F050503B    5649
F050601B    1331
F050701B    1333
F050801B    1331
F051101B    2856
F051201B    3421
F053301B    2277
F051301B    2277
F051401B     279
F051501B     279
F051601B     266
F051701B     279
F051801B    1623
F051901B    1603
F052001B    1669
F052101B    2304
F052201B     279
F052301B    1597
F052401B    1603
F053001B    3115
F053003B    5708
F053101B    5385
F053103B    7871
Indnme       133
dtype: int64

In [42]:
data7else

,Stkcd,Accper,Typrep,Indcd,F050101B,F050103B,F050201B,F050203B,F050301B,F050303B,...,F052001B,F052101B,F052201B,F052301B,F052401B,F053001B,F053003B,F053101B,F053103B,Indnme
68,000002,2010-03-31,A,K70,0.011167,0.011589,0.007924,0.008223,0.008347,0.008672,...,0.094356,0.250149,-0.023045,0.220814,0.220814,0.028902,0.029509,0.029107,0.029718,房地产业
70,000002,2010-06-30,A,K70,0.027471,0.029582,0.019692,0.021205,0.020718,0.022347,...,0.085349,0.310279,-0.013845,0.266415,0.262995,0.070714,0.072911,0.069552,0.071713,房地产业
72,000002,2010-09-30,A,K70,0.02852,0.032929,0.020356,0.023503,0.0213,0.024687,...,0.096967,0.27983,-0.009816,0.23949,0.23949,0.081281,0.084296,0.080699,0.083692,房地产业
74,000002,2010-12-31,A,K70,0.057712,0.070461,0.040993,0.050048,0.043011,0.052641,...,0.087347,0.297572,-0.010755,0.247289,0.245396,0.164655,0.178489,0.164804,0.17865,房地产业
76,000002,2011-03-31,A,K70,0.007749,0.008087,0.005056,0.005277,0.005297,0.005533,...,0.138696,0.267128,0.004857,0.228813,0.228813,0.026467,0.026851,0.027352,0.027748,房地产业
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335061,900957,2021-09-30,A,K70,0.041654,0.042263,0.020199,0.020494,0.070823,0.077253,...,0.298083,0.340684,0.0,0.502692,0.502692,0.04042,0.041254,0.04042,0.041254,房地产业
335062,900957,2021-12-31,A,K70,0.05783,0.058257,0.02701,0.027209,0.096581,0.103713,...,0.317993,0.353257,0.0,0.868255,0.52349,0.052634,0.054057,0.052634,0.054057,房地产业
335064,900957,2022-03-31,A,K70,0.014125,0.014191,0.007526,0.007561,0.02587,0.026502,...,0.261698,0.393692,0.0,0.49795,0.49795,0.014581,0.014688,0.014581,0.014688,房地产业
335065,900957,2022-06-30,A,K70,0.034897,0.035264,0.02106,0.021281,0.069071,0.072778,...,0.239495,0.554042,0.0,0.862742,0.563879,0.040262,0.041089,0.040262,0.041089,房地产业
335067,900957,2022-09-30,A,K70,0.049618,0.050305,0.028754,0.029152,0.09111,0.097865,...,0.251325,0.508394,0.0,0.552432,0.552432,0.054496,0.056023,0.054496,0.056023,房地产业

In [43]:
col7else = str(list(data7else.columns))
index7else = colname7[data7else.columns]

In [44]:
index7else

Stkcd                     股票代码
Accper                  统计截止日期
Typrep                  报表类型编码
Indcd                     行业代码
F050101B                资产报酬率A
F050103B                资产报酬率C
F050201B         总资产净利润率(ROA)A
F050203B         总资产净利润率(ROA)C
F050301B             流动资产净利润率A
F050303B             流动资产净利润率C
F050401B             固定资产净利润率A
F050403B             固定资产净利润率C
F050501B          净资产收益率（ROE）A
F050503B          净资产收益率（ROE）C
F050601B           息税前利润（EBIT）
F050701B                息前税后利润
F050801B     息税折旧摊销前收入（EBITDA）
F051101B           息税前利润与资产总额比
F051201B         投入资本回报率（ROIC）
F053301B                 营业毛利率
F051301B                 营业成本率
F051401B                 营业利润率
F051501B                 营业净利率
F051601B                总营业成本率
F051701B                 销售费用率
F051801B                 管理费用率
F051901B                 财务费用率
F052001B               销售期间费用率
F052101B               成本费用利润率
F052201B           资产减值损失／营业收入
F052301B          息税折旧摊销前营业利润率
F052401B              息税前营业利润率
F053001B    归属于母公司净资产收益率（ROE）A
F053003B    归属于母公司净资产收益率（ROE）C
F053101B          归属于母公司综合收益率A
F053103B          归属于母公司综合收益率C
Indnme                    行业名称
Name: 0, dtype: object

#### test the nulls

In [47]:
# cnt = 0
# count = []
# for i in data.isnull ().sum ():
#     if i == 0:
#         cnt = cnt + 1
#     count += [i]
# count = count[3:]

In [48]:
# name = data.iloc[0,3:]
# dic = {n:c for n,c in zip(name, count)}
# dic

# Pearson correlation coefficient

In [70]:
def delcol(df):
    df = df.apply(lambda x:x.astype(float))
    corr = df.corr()
    delSimCol = []
    colNum = corr.shape[0]###列
    print(corr.shape[1])
    print(colNum)
    names = corr.columns
    for i in range(colNum):
        for j in range(i+1,colNum):
            if abs(corr.iloc[i,j]) > 0.8:
                delSimCol.append((names[i],names[j]))
    print('经过筛选得到的相似的属性为：\n',delSimCol)
    delCol = [i[1] for i in delSimCol]
    delCol = list(set(delCol))
    df.drop(delCol,axis=1,inplace = True) # 删除列
    return df

## 1. Risk Level

In [115]:
Risk_rank_df = data1.iloc[:,4:-1]
Risk_rank_df = delcol(Risk_rank_df)

3
3
经过筛选得到的相似的属性为：
 [('F070101B', 'F070301B')]

In [52]:
col1 = str(list(Risk_rank_df.columns))
index1 = colname1[Risk_rank_df.columns]

In [53]:
index1

F070101B    财务杠杆
F070201B    经营杠杆
Name: 0, dtype: object

In [54]:
with open('fxsp_index.txt', 'a+', encoding='utf-8') as f:
    f.write(col1 + "\n")
    for i in index1:
        f.write(i + '\n')
    f.close()

In [55]:
Risk_rank_df["stock"] = data1.iloc[:,0]
Risk_rank_df["date"] = data1.iloc[:,1]

In [56]:
Risk_rank_df

        F070101B  F070201B   stock        date
2       1.000000  1.065726  000001  2012-06-30
4       1.000000  1.000000  000001  2012-09-30
6       1.000000  1.071584  000001  2012-12-31
8       1.000000  1.000000  000001  2013-03-31
9       1.000000  1.069049  000001  2013-06-30
...          ...       ...     ...         ...
284760  1.932653  1.000000  900957  2021-09-30
284761  1.947996  1.658589  900957  2021-12-31
284763  1.732356  1.000000  900957  2022-03-31
284764  1.557705  1.530011  900957  2022-06-30
284766  1.605945  1.000000  900957  2022-09-30

[154083 rows x 4 columns]

## 2. Stock Indicators

In [116]:
pershare_indicators_df = data2.iloc[:,4:-1]
pershare_indicators_df = delcol(pershare_indicators_df)

27
27
经过筛选得到的相似的属性为：
 [('F090101B', 'F090103B'), ('F090101B', 'F090201B'), ('F090101B', 'F090301B'), ('F090101B', 'F090401B'), ('F090101B', 'F090701B'), ('F090101B', 'F090801B'), ('F090101B', 'F090901B'), ('F090101B', 'F091001A'), ('F090101B', 'F091101A'), ('F090101B', 'F091201A'), ('F090101B', 'F091501A'), ('F090101B', 'F091701A'), ('F090101B', 'F092301B'), ('F090101B', 'F092301C'), ('F090101B', 'F092601B'), ('F090103B', 'F090201B'), ('F090103B', 'F090301B'), ('F090103B', 'F090401B'), ('F090103B', 'F090701B'), ('F090103B', 'F090801B'), ('F090103B', 'F090901B'), ('F090103B', 'F091001A'), ('F090103B', 'F091101A'), ('F090103B', 'F091201A'), ('F090103B', 'F091501A'), ('F090103B', 'F091701A'), ('F090103B', 'F092301B'), ('F090103B', 'F092301C'), ('F090103B', 'F092601B'), ('F090201B', 'F090301B'), ('F090201B', 'F090401B'), ('F090201B', 'F090501B'), ('F090201B', 'F090601B'), ('F090201B', 'F090701B'), ('F090201B', 'F090801B'), ('F090201B', 'F090901B'), ('F090201B', 'F091001A'), ('F090201B', 'F091101A'), ('F090201B', 'F091201A'), ('F090201B', 'F091501A'), ('F090201B', 'F091701A'), ('F090201B', 'F092601B'), ('F090301B', 'F090401B'), ('F090301B', 'F090701B'), ('F090301B', 'F090801B'), ('F090301B', 'F090901B'), ('F090301B', 'F091001A'), ('F090301B', 'F091101A'), ('F090301B', 'F091201A'), ('F090301B', 'F091501A'), ('F090301B', 'F091701A'), ('F090301B', 'F092301B'), ('F090301B', 'F092301C'), ('F090301B', 'F092601B'), ('F090401B', 'F090501B'), ('F090401B', 'F090601B'), ('F090401B', 'F090701B'), ('F090401B', 'F090801B'), ('F090401B', 'F090901B'), ('F090401B', 'F091001A'), ('F090401B', 'F091101A'), ('F090401B', 'F091201A'), ('F090401B', 'F091501A'), ('F090401B', 'F091701A'), ('F090401B', 'F092601B'), ('F090501B', 'F090601B'), ('F090501B', 'F091001A'), ('F090501B', 'F091101A'), ('F090501B', 'F091201A'), ('F090501B', 'F091501A'), ('F090501B', 'F091701A'), ('F090501B', 'F091801B'), ('F090501B', 'F092201B'), ('F090501B', 'F092301B'), ('F090501B', 'F092301C'), ('F090501B', 'F092601B'), ('F090601B', 'F091001A'), ('F090601B', 'F091101A'), ('F090601B', 'F091201A'), ('F090601B', 'F091501A'), ('F090601B', 'F091701A'), ('F090601B', 'F091801B'), ('F090601B', 'F092201B'), ('F090601B', 'F092301B'), ('F090601B', 'F092301C'), ('F090601B', 'F092601B'), ('F090701B', 'F090801B'), ('F090701B', 'F090901B'), ('F090701B', 'F091001A'), ('F090701B', 'F091101A'), ('F090701B', 'F091201A'), ('F090701B', 'F091501A'), ('F090701B', 'F091701A'), ('F090701B', 'F092601B'), ('F090801B', 'F090901B'), ('F090801B', 'F091001A'), ('F090801B', 'F091101A'), ('F090801B', 'F091201A'), ('F090801B', 'F091501A'), ('F090801B', 'F091701A'), ('F090801B', 'F092601B'), ('F090901B', 'F091001A'), ('F090901B', 'F091101A'), ('F090901B', 'F091201A'), ('F090901B', 'F091501A'), ('F090901B', 'F091701A'), ('F090901B', 'F092301B'), ('F090901B', 'F092301C'), ('F090901B', 'F092601B'), ('F091001A', 'F091101A'), ('F091001A', 'F091201A'), ('F091001A', 'F091501A'), ('F091001A', 'F091701A'), ('F091001A', 'F091801B'), ('F091001A', 'F092201B'), ('F091001A', 'F092301B'), ('F091001A', 'F092301C'), ('F091001A', 'F092601B'), ('F091101A', 'F091201A'), ('F091101A', 'F091501A'), ('F091101A', 'F091701A'), ('F091101A', 'F091801B'), ('F091101A', 'F092301B'), ('F091101A', 'F092301C'), ('F091101A', 'F092601B'), ('F091201A', 'F091501A'), ('F091201A', 'F091701A'), ('F091201A', 'F091801B'), ('F091201A', 'F092301B'), ('F091201A', 'F092301C'), ('F091201A', 'F092601B'), ('F091501A', 'F091701A'), ('F091501A', 'F091801B'), ('F091501A', 'F092301B'), ('F091501A', 'F092301C'), ('F091501A', 'F092601B'), ('F091701A', 'F091801B'), ('F091701A', 'F092201B'), ('F091701A', 'F092301B'), ('F091701A', 'F092301C'), ('F091701A', 'F092601B'), ('F091801B', 'F092201B'), ('F091801B', 'F092301B'), ('F091801B', 'F092301C'), ('F091801B', 'F092601B'), ('F091901B', 'F092101B'), ('F092001B', 'F092001C'), ('F092101B', 'F092201B'), ('F092201B', 'F092601B'), ('F092301B', 'F092301C'), ('F092301B', 'F092601B'), ('F092301C', 'F092601B')]

In [58]:
col2 = str(list(pershare_indicators_df.columns))
index2 = colname2[pershare_indicators_df.columns]

In [59]:
index2

F090101B          每股收益1
F090501B        每股营业总收入
F091301A         每股资本公积
F091401A         每股盈余公积
F091601A         每股留存收益
F091901B    每股投资活动现金净流量
F092001B    每股筹资活动现金净流量
Name: 0, dtype: object

In [60]:
with open('mgzb_index.txt', 'a+', encoding='utf-8') as f:
    f.write(col2 + "\n")
    for i in index2:
        f.write(i + '\n')
    f.close()

## 3. Solvency

In [71]:
Solvency_analysis_j66_df = data3j66.iloc[:,4:-1]
Solvency_analysis_j66_df = delcol(Solvency_analysis_j66_df)

13
13
经过筛选得到的相似的属性为：
 [('F011201A', 'F011401A'), ('F011201A', 'F011801A'), ('F011201A', 'F012601B'), ('F011301A', 'F011501A'), ('F011301A', 'F011901A'), ('F011301A', 'F012001A'), ('F011401A', 'F011801A'), ('F011401A', 'F012601B'), ('F011501A', 'F011901A'), ('F011501A', 'F012001A'), ('F011601A', 'F011701A'), ('F011601A', 'F012601B'), ('F011601A', 'F020502A'), ('F011701A', 'F012601B'), ('F011701A', 'F020502A'), ('F011901A', 'F012001A'), ('F012601B', 'F020502A')]

In [72]:
Solvency_analysis_j66_df

        F011201A  F011301A   F011601A  F012301B  F012501B
2       0.964335       0.0  28.038557  0.014778  0.896348
3       0.951279       0.0  20.525162 -0.005224  0.911475
4       0.952384       0.0  21.001152  0.017483  0.922687
5       0.954349       0.0  21.905454  0.034481  0.929486
6       0.955483       0.0  22.463473  0.029130  0.934763
...          ...       ...        ...       ...       ...
298425  0.914190       0.0  11.653670 -0.024871  0.932587
298426  0.916407       0.0  11.962730 -0.013044  0.938747
298428  0.916797       0.0  12.018802  0.005401  0.936612
298429  0.918940       0.0  12.336573  0.020712  0.940355
298431  0.917593       0.0  12.134838  0.016088  0.940867

[1356 rows x 5 columns]

In [73]:
col3j66 = str(list(Solvency_analysis_j66_df.columns))
index3j66 = colname3[Solvency_analysis_j66_df.columns]

In [74]:
index3j66

F011201A                 资产负债率
F011301A             长期借款与总资产比
F011601A                  权益乘数
F012301B    经营活动产生的现金流量净额／负债合计
F012501B             负债与权益市价比率
Name: 0, dtype: object

In [64]:
Solvency_analysis_else_df = data3else.iloc[:,4:-1]
Solvency_analysis_else_df = delcol(Solvency_analysis_else_df)

16
16
经过筛选得到的相似的属性为：
 [('F010101A', 'F010201A'), ('F010101A', 'F010301A'), ('F010101A', 'F010401A'), ('F010101A', 'F011801A'), ('F010201A', 'F010301A'), ('F010201A', 'F010401A'), ('F010201A', 'F011801A'), ('F010301A', 'F010401A'), ('F010301A', 'F011801A'), ('F010401A', 'F011801A'), ('F011201A', 'F011401A'), ('F011601A', 'F011701A')]

In [109]:
Solvency_analysis_else_df.corr()

,F010101A,F010601A,F010801B,F011201A,F011301A,F011501A,F011601A,F011901A,F012001A,F012101A
F010101A,1.000000,0.004966,-0.348190,-0.026261,-0.046731,-0.034192,-2.294895e-03,-0.004825,-0.002837,2.380209e-04
F010601A,0.004966,1.000000,-0.000156,0.000827,0.039819,-0.018748,1.008218e-03,0.005644,0.001375,1.644266e-03
F010801B,-0.348190,-0.000156,1.000000,-0.000437,0.000577,-0.000306,-5.757401e-05,0.000005,-0.000008,-5.280971e-05
F011201A,-0.026261,0.000827,-0.000437,1.000000,0.062769,0.533959,3.540545e-03,-0.011662,0.005243,2.319623e-04
F011301A,-0.046731,0.039819,0.000577,0.062769,1.000000,0.213705,1.553742e-02,0.064200,0.045878,2.844026e-03
F011501A,-0.034192,-0.018748,-0.000306,0.533959,0.213705,1.000000,6.271467e-03,-0.027242,0.012967,-1.385784e-03
F011601A,-0.002295,0.001008,-0.000058,0.003541,0.015537,0.006271,1.000000e+00,0.002349,0.601989,6.359975e-07
F011901A,-0.004825,0.005644,0.000005,-0.011662,0.064200,-0.027242,2.349097e-03,1.000000,0.005427,6.282117e-04
F012001A,-0.002837,0.001375,-0.000008,0.005243,0.045878,0.012967,6.019894e-01,0.005427,1.000000,1.361500e-04
F012101A,0.000238,0.001644,-0.000053,0.000232,0.002844,-0.001386,6.359975e-07,0.000628,0.000136,1.000000e+00

In [65]:
col3else = str(list(Solvency_analysis_else_df.columns))
index3else = colname3[Solvency_analysis_else_df.columns]

In [66]:
index3else

F010101A                  流动比率
F010601A                  营运资金
F010801B    经营活动产生的现金流量净额／流动负债
F011201A                 资产负债率
F011301A             长期借款与总资产比
F011501A             有形资产带息债务比
F011601A                  权益乘数
F011901A               长期资本负债率
F012001A              长期负债权益比率
F012101A           长期债务与营运资金比率
Name: 0, dtype: object

In [67]:
with open('cznl_index.txt', 'a+', encoding='utf-8') as f:
    f.write("J66:" + "\n")
    f.write(col3j66 + "\n")
    for i in index3j66:
        f.write(i + '\n')
        
    f.write("ELSE:" + "\n")
    f.write(col3else + "\n")
    for i in index3else:
        f.write(i + '\n')
    f.close()

## 4. Development Capacity

In [68]:
Dvlp_cap_j66_df = data4j66.iloc[:,4:-1]
Dvlp_cap_j66_df = delcol(Dvlp_cap_j66_df)

44
44
经过筛选得到的相似的属性为：
 [('F080101A', 'F080301A'), ('F080101A', 'F082701A'), ('F080102A', 'F080201A'), ('F080102A', 'F080302A'), ('F080102A', 'F080401A'), ('F080102A', 'F082702A'), ('F080102A', 'F082703A'), ('F080201A', 'F080302A'), ('F080201A', 'F080401A'), ('F080201A', 'F082702A'), ('F080201A', 'F082703A'), ('F080301A', 'F082701A'), ('F080302A', 'F080401A'), ('F080302A', 'F082702A'), ('F080302A', 'F082703A'), ('F080401A', 'F082702A'), ('F080401A', 'F082703A'), ('F080502A', 'F080503A'), ('F080602A', 'F080603A'), ('F080701B', 'F081001B'), ('F080701B', 'F081101B'), ('F080701B', 'F081201B'), ('F080702B', 'F081102B'), ('F080702B', 'F081202B'), ('F080702B', 'F081003B'), ('F080702B', 'F081103B'), ('F080702B', 'F080803B'), ('F080702B', 'F081203B'), ('F080802B', 'F080902B'), ('F080802B', 'F080803B'), ('F080902B', 'F080803B'), ('F081001B', 'F081101B'), ('F081001B', 'F081201B'), ('F081002B', 'F081102B'), ('F081002B', 'F081301B'), ('F081002B', 'F080703B'), ('F081002B', 'F081003B'), ('F081002B', 'F081103B'), ('F081002B', 'F080803B'), ('F081101B', 'F081201B'), ('F081102B', 'F081202B'), ('F081102B', 'F081301B'), ('F081102B', 'F082601B'), ('F081102B', 'F081003B'), ('F081102B', 'F081103B'), ('F081102B', 'F080803B'), ('F081102B', 'F081203B'), ('F081102B', 'F082602B'), ('F081202B', 'F081301B'), ('F081202B', 'F082601B'), ('F081202B', 'F081003B'), ('F081202B', 'F081103B'), ('F081202B', 'F080803B'), ('F081202B', 'F081203B'), ('F081202B', 'F082602B'), ('F081301B', 'F081003B'), ('F081301B', 'F081103B'), ('F081301B', 'F081203B'), ('F081602C', 'F081701B'), ('F081602C', 'F081603B'), ('F081701B', 'F081603B'), ('F082601B', 'F082602B'), ('F082601B', 'F082603B'), ('F082702A', 'F082703A'), ('F082801A', 'F082803A'), ('F081003B', 'F081103B'), ('F081003B', 'F080803B'), ('F081003B', 'F081203B'), ('F081103B', 'F080803B'), ('F081103B', 'F081203B'), ('F080803B', 'F081203B'), ('F082602B', 'F082603B')]

In [69]:
col4j66 = str(list(Dvlp_cap_j66_df.columns))
index4j66 = colname4[Dvlp_cap_j66_df.columns]

In [70]:
index4j66

F080101A      资本保值增值率A
F080102A      资本保值增值率B
F080501A      固定资产增长率A
F080502A      固定资产增长率B
F080601A       总资产增长率A
F080602A       总资产增长率B
F080701B    净资产收益率增长率A
F080702B    净资产收益率增长率B
F080801B    基本每股收益增长率A
F080802B    基本每股收益增长率B
F081002B       净利润增长率B
F081401B       综合收益增长率
F081601B      营业收入增长率A
F081602C      营业收入增长率B
F081801B      营业总成本增长率
F082801A     每股净资产增长率B
F082802A     每股净资产增长率A
Name: 0, dtype: object

In [111]:
Dvlp_cap_else_df.corr()

,F080101A,F080102A,F080501A,F080502A,F080601A,F080602A,F081601B,F081602C,F081801B,F081901B,F082001B,F082101B,F082601B,F080703B,F081003B,F081103B,F080803B,F081203B
F080101A,1.000000,0.000033,0.207897,0.012559,0.433835,0.009532,0.018043,-0.000120,0.001243,0.000524,0.004005,0.003115,0.403978,0.000831,0.023706,0.057125,0.332361,0.002934
F080102A,0.000033,1.000000,0.016828,0.117799,0.000543,0.000066,0.004615,0.019292,0.274869,0.020403,0.154569,0.000113,0.000137,0.000124,0.004703,0.010203,0.033595,0.004158
F080501A,0.207897,0.016828,1.000000,0.240916,0.299479,0.007576,0.001505,-0.000025,-0.000102,0.000119,0.000348,-0.000025,0.070045,0.000011,0.004950,0.012753,0.073627,0.000006
F080502A,0.012559,0.117799,0.240916,1.000000,0.077293,0.134014,0.003672,0.030687,0.230369,0.006892,0.035292,0.001992,0.017022,0.000053,0.001646,0.006177,0.019552,0.002672
F080601A,0.433835,0.000543,0.299479,0.077293,1.000000,0.023967,0.007022,0.001607,0.007967,0.000808,0.025641,-0.018476,0.263112,0.002162,0.023961,0.052409,0.298448,0.009095
F080602A,0.009532,0.000066,0.007576,0.134014,0.023967,1.000000,0.015241,0.074709,0.220602,0.057008,0.204992,0.002578,0.007077,0.000169,0.007624,0.015746,0.030697,0.009884
F081601B,0.018043,0.004615,0.001505,0.003672,0.007022,0.015241,1.000000,0.016285,0.035955,0.017383,0.043432,0.008721,0.000035,0.000087,0.001354,0.002889,0.005545,0.002334
F081602C,-0.000120,0.019292,-0.000025,0.030687,0.001607,0.074709,0.016285,1.000000,0.204948,0.038333,0.036279,0.005431,0.000086,0.000051,0.000491,0.000986,0.002397,0.000876
F081801B,0.001243,0.274869,-0.000102,0.230369,0.007967,0.220602,0.035955,0.204948,1.000000,0.266083,0.586189,0.017331,0.000713,0.000165,0.011836,0.024363,0.048153,0.018000
F081901B,0.000524,0.020403,0.000119,0.006892,0.000808,0.057008,0.017383,0.038333,0.266083,1.000000,0.046444,0.003035,0.000224,0.000080,0.000941,0.001653,0.002206,0.002357
F082001B,0.004005,0.154569,0.000348,0.035292,0.025641,0.204992,0.043432,0.036279,0.586189,0.046444,1.000000,0.026353,0.001248,0.002134,0.016816,0.030538,0.038219,0.025993
F082101B,0.003115,0.000113,-0.000025,0.001992,-0.018476,0.002578,0.008721,0.005431,0.017331,0.003035,0.026353,1.000000,0.002199,0.000298,0.000723,0.001198,0.005247,0.000620
F082601B,0.403978,0.000137,0.070045,0.017022,0.263112,0.007077,0.000035,0.000086,0.000713,0.000224,0.001248,0.002199,1.000000,-0.000195,0.032200,0.081414,0.469490,0.000969
F080703B,0.000831,0.000124,0.000011,0.000053,0.002162,0.000169,0.000087,0.000051,0.000165,0.000080,0.002134,0.000298,-0.000195,1.000000,0.738054,0.005046,0.039084,0.002641
F081003B,0.023706,0.004703,0.004950,0.001646,0.023961,0.007624,0.001354,0.000491,0.011836,0.000941,0.016816,0.000723,0.032200,0.738054,1.000000,0.032778,0.083895,0.021999
F081103B,0.057125,0.010203,0.012753,0.006177,0.052409,0.015746,0.002889,0.000986,0.024363,0.001653,0.030538,0.001198,0.081414,0.005046,0.032778,1.000000,0.139422,0.061838
F080803B,0.332361,0.033595,0.073627,0.019552,0.298448,0.030697,0.005545,0.002397,0.048153,0.002206,0.038219,0.005247,0.469490,0.039084,0.083895,0.139422,1.000000,0.042924
F081203B,0.002934,0.004158,0.000006,0.002672,0.009095,0.009884,0.002334,0.000876,0.018000,0.002357,0.025993,0.000620,0.000969,0.002641,0.021999,0.061838,0.042924,1.000000

In [128]:
Dvlp_cap_else_df = data4else.iloc[:,4:-1]
Dvlp_cap_else_df = delcol(Dvlp_cap_else_df)

33
33
经过筛选得到的相似的属性为：
 [('F080101A', 'F080301A'), ('F080101A', 'F082701A'), ('F080101A', 'F082802A'), ('F080102A', 'F080201A'), ('F080102A', 'F080302A'), ('F080102A', 'F080401A'), ('F080102A', 'F082702A'), ('F080102A', 'F082801A'), ('F080102A', 'F082703A'), ('F080102A', 'F082803A'), ('F080201A', 'F080302A'), ('F080201A', 'F080401A'), ('F080201A', 'F082702A'), ('F080201A', 'F082801A'), ('F080201A', 'F082703A'), ('F080201A', 'F082803A'), ('F080301A', 'F082701A'), ('F080301A', 'F082802A'), ('F080302A', 'F080401A'), ('F080302A', 'F082702A'), ('F080302A', 'F082801A'), ('F080302A', 'F082703A'), ('F080302A', 'F082803A'), ('F080401A', 'F082702A'), ('F080401A', 'F082801A'), ('F080401A', 'F082703A'), ('F080401A', 'F082803A'), ('F080502A', 'F080503A'), ('F080602A', 'F080603A'), ('F081602C', 'F081701B'), ('F081602C', 'F081603B'), ('F081701B', 'F081603B'), ('F082601B', 'F082602B'), ('F082701A', 'F082802A'), ('F082702A', 'F082801A'), ('F082702A', 'F082703A'), ('F082702A', 'F082803A'), ('F082801A', 'F082703A'), ('F082801A', 'F082803A'), ('F082703A', 'F082803A')]

In [129]:
col4else = str(list(Dvlp_cap_else_df.columns))
index4else = colname4[Dvlp_cap_else_df.columns]

In [130]:
index4else

F080101A      资本保值增值率A
F080102A      资本保值增值率B
F080501A      固定资产增长率A
F080502A      固定资产增长率B
F080601A       总资产增长率A
F080602A       总资产增长率B
F081601B      营业收入增长率A
F081602C      营业收入增长率B
F081801B      营业总成本增长率
F081901B       销售费用增长率
F082001B       管理费用增长率
F082101B          应计项目
F082601B        可持续增长率
F080703B    净资产收益率增长率C
F081003B       净利润增长率C
F081103B      利润总额增长率C
F080803B    基本每股收益增长率C
F081203B      营业利润增长率C
Name: 0, dtype: object

In [74]:
with open('fznl_index.txt', 'a+', encoding='utf-8') as f:
    f.write("J66:" + "\n")
    f.write(col4j66 + "\n")
    for i in index4j66:
        f.write(i + '\n')
        
    f.write("ELSE:" + "\n")
    f.write(col4else + "\n")
    for i in index4else:
        f.write(i + '\n')
    f.close()

## 5. Operating Capacity

In [131]:
Operating_cap_j66_df = data5j66.iloc[:,4:-1]
Operating_cap_j66_df = delcol(Operating_cap_j66_df)

24
24
经过筛选得到的相似的属性为：
 [('F041002B', 'F041003B'), ('F041002B', 'F041005C'), ('F041003B', 'F041004B'), ('F041004B', 'F041005C'), ('F041401B', 'F041402B'), ('F041401B', 'F041403B'), ('F041401B', 'F041404B'), ('F041401B', 'F041405C'), ('F041402B', 'F041403B'), ('F041402B', 'F041404B'), ('F041402B', 'F041405C'), ('F041403B', 'F041404B'), ('F041403B', 'F041405C'), ('F041404B', 'F041405C'), ('F041601B', 'F041801B'), ('F041701B', 'F041702B'), ('F041701B', 'F041703B'), ('F041701B', 'F041801B'), ('F041702B', 'F041703B'), ('F041702B', 'F041801B'), ('F041702B', 'F041802B'), ('F041702B', 'F041803B'), ('F041703B', 'F041801B'), ('F041703B', 'F041802B'), ('F041703B', 'F041803B'), ('F041704B', 'F041705C'), ('F041801B', 'F041802B'), ('F041801B', 'F041803B'), ('F041802B', 'F041803B'), ('F041804B', 'F041805C')]

In [132]:
col5j66 = str(list(Operating_cap_j66_df.columns))
index5j66 = colname5[Operating_cap_j66_df.columns]

In [133]:
index5j66

F040101B        应收账款与收入比
F040401B          存货与收入比
F041001B    现金及现金等价物周转率A
F041002B    现金及现金等价物周转率B
F041301B        固定资产与收入比
F041401B        固定资产周转率A
F041601B           资本密集度
F041701B         总资产周转率A
F041704B         总资产周转率D
F041804B        股东权益周转率D
Name: 0, dtype: object

In [124]:
Operating_cap_j66_df.corr()

,F040101B,F040401B,F041001B,F041002B,F041301B,F041401B,F041601B,F041701B,F041704B,F041804B
F040101B,1.000000,NaN,-0.017197,-0.146000,0.198968,-0.033407,0.280496,-0.152398,-0.011511,0.210022
F040401B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
F041001B,-0.017197,NaN,1.000000,0.011575,-0.031025,0.787268,-0.005922,0.621833,0.198354,0.192138
F041002B,-0.146000,NaN,0.011575,1.000000,-0.182952,0.042398,-0.063171,0.366145,0.267671,-0.123526
F041301B,0.198968,NaN,-0.031025,-0.182952,1.000000,-0.145953,0.778808,-0.360187,-0.200700,-0.175665
F041401B,-0.033407,NaN,0.787268,0.042398,-0.145953,1.000000,-0.025797,0.672765,0.290461,0.161177
F041601B,0.280496,NaN,-0.005922,-0.063171,0.778808,-0.025797,1.000000,-0.112579,-0.184870,-0.256408
F041701B,-0.152398,NaN,0.621833,0.366145,-0.360187,0.672765,-0.112579,1.000000,0.463544,0.329531
F041704B,-0.011511,NaN,0.198354,0.267671,-0.200700,0.290461,-0.184870,0.463544,1.000000,0.664796
F041804B,0.210022,NaN,0.192138,-0.123526,-0.175665,0.161177,-0.256408,0.329531,0.664796,1.000000

In [134]:
Operating_cap_else_df = data5else.iloc[:,4:-1]
Operating_cap_else_df = delcol(Operating_cap_else_df)

42
42
经过筛选得到的相似的属性为：
 [('F040101B', 'F040301B'), ('F040101B', 'F040302B'), ('F040101B', 'F040303B'), ('F040202B', 'F040203B'), ('F040202B', 'F040204B'), ('F040203B', 'F040204B'), ('F040301B', 'F040302B'), ('F040301B', 'F040303B'), ('F040302B', 'F040303B'), ('F040501B', 'F040502B'), ('F040501B', 'F040503B'), ('F040501B', 'F040504B'), ('F040502B', 'F040503B'), ('F040502B', 'F040504B'), ('F040503B', 'F040504B'), ('F040601B', 'F040602B'), ('F040601B', 'F040603B'), ('F040601B', 'F040701B'), ('F040601B', 'F040702B'), ('F040601B', 'F040703B'), ('F040602B', 'F040603B'), ('F040602B', 'F040701B'), ('F040602B', 'F040702B'), ('F040602B', 'F040703B'), ('F040603B', 'F040701B'), ('F040603B', 'F040702B'), ('F040603B', 'F040703B'), ('F040701B', 'F040702B'), ('F040701B', 'F040703B'), ('F040702B', 'F040703B'), ('F040803B', 'F040804B'), ('F041003B', 'F041004B'), ('F041101B', 'F041601B'), ('F041201B', 'F041203B'), ('F041201B', 'F041204B'), ('F041203B', 'F041204B'), ('F041401B', 'F041501B'), ('F041403B', 'F041404B'), ('F041503B', 'F041504B'), ('F041701B', 'F041703B'), ('F041701B', 'F041704B'), ('F041703B', 'F041704B'), ('F041803B', 'F041804B')]

In [135]:
col5else = str(list(Operating_cap_else_df.columns))
index5else = colname5[Operating_cap_else_df.columns]

In [136]:
index5else

F040101B        应收账款与收入比
F040201B        应收账款周转率A
F040202B        应收账款周转率B
F040401B          存货与收入比
F040501B          存货周转率A
F040601B         存货周转天数A
F040803B        应付账款周转率C
F041001B    现金及现金等价物周转率A
F041003B    现金及现金等价物周转率C
F041101B        流动资产与收入比
F041201B        流动资产周转率A
F041301B        固定资产与收入比
F041401B        固定资产周转率A
F041403B        固定资产周转率C
F041503B       非流动资产周转率C
F041701B         总资产周转率A
F041801B        股东权益周转率A
F041803B        股东权益周转率C
Name: 0, dtype: object

In [81]:
with open('jynl_index.txt', 'a+', encoding='utf-8') as f:
    f.write("J66:" + "\n")
    f.write(col5j66 + "\n")
    for i in index5j66:
        f.write(i + '\n')
        
    f.write("ELSE:" + "\n")
    f.write(col5else + "\n")
    for i in index5else:
        f.write(i + '\n')
    f.close()

## 6. Cash Flow Analysis

In [15]:
Cashflow_analysis_j66_df = data6j66.iloc[:,4:-1]
Cashflow_analysis_j66_df = delcol(Cashflow_analysis_j66_df)

18
18
经过筛选得到的相似的属性为：
 [('F060101B', 'F060301B'), ('F060101B', 'F060401B'), ('F060101B', 'F061701B'), ('F060101C', 'F060301C'), ('F060101C', 'F060401C'), ('F060301B', 'F060401B'), ('F060301C', 'F060401C'), ('F060401B', 'F061701B'), ('F061302B', 'F061402B'), ('F061302C', 'F061402C')]

In [16]:
col6j66 = str(list(Cashflow_analysis_j66_df.columns))
index6j66 = colname6[Cashflow_analysis_j66_df.columns]

In [19]:
Cashflow_analysis_j66_df

,F060101B,F060101C,F060901B,F060901C,F061001B,F061001C,F061302B,F061302C,F061801B,F062001B,F062201B
2,5.455636,6.943404,0.000000e+00,0.000000e+00,-3.700250e+08,-5.793940e+08,1.858771e+09,1.821864e+10,5.736412,18.160879,25.552068
3,-1.000105,4.400779,-4.597000e+08,-4.597000e+08,6.931130e+09,6.467568e+09,-4.871832e+09,6.132930e+09,-1.065799,-11.135642,23.588485
4,2.234881,7.022928,-2.336700e+07,-2.353900e+07,6.442869e+09,6.357685e+09,3.114408e+09,1.400656e+10,2.439711,10.039592,22.409318
5,3.460683,3.460683,-2.370200e+07,-2.370200e+07,6.382268e+09,6.382268e+09,7.085759e+09,7.085759e+09,3.587739,15.681335,23.247679
6,8.886254,4.851394,-3.725500e+08,-3.725500e+08,0.000000e+00,6.752293e+09,1.356452e+10,1.879151e+10,9.444356,695.939426,27.787583
...,...,...,...,...,...,...,...,...,...,...,...
298392,-3.183296,-4.533044,1.864976e+09,4.130556e+09,-4.551450e+08,-3.751000e+08,-2.722111e+09,-3.220000e+09,-4.331821,-5.455454,3.882618
298393,-1.531668,-1.531668,3.366828e+09,3.366828e+09,-5.494090e+08,-5.494090e+08,-4.527579e+09,-4.527579e+09,-2.612959,-2.288604,4.219809
298395,2.568633,-1.260812,6.561410e+08,2.982862e+09,-5.591300e+07,-5.851330e+08,-1.084444e+09,-3.386478e+09,3.918013,5.268323,5.300356
298396,3.704880,3.783467,-3.313130e+08,-1.122578e+09,-3.953340e+08,-5.386840e+08,1.052285e+09,2.066253e+09,6.574568,6.158301,5.459111
298398,1.966319,2.927927,5.941200e+08,2.095972e+09,-4.951230e+08,-5.893870e+08,3.003700e+08,-1.505098e+09,3.407565,3.791270,4.965086

In [18]:
index6j66

F060101B           净利润现金净含量
F060101C        净利润现金净含量TTM
F060901B       筹资活动债权人现金净流量
F060901C    筹资活动债权人现金净流量TTM
F061001B        筹资活动股东现金净流量
F061001C     筹资活动股东现金净流量TTM
F061302B             公司现金流2
F061302C          公司现金流TTM2
F061801B               营运指数
F062001B             现金适合比率
F062201B           现金满足投资比率
Name: 0, dtype: object

In [146]:
Cashflow_analysis_else_df = data6else.iloc[:,4:-1]
Cashflow_analysis_else_df = delcol(Cashflow_analysis_else_df)

20
20
经过筛选得到的相似的属性为：
 [('F061001B', 'F061001C')]

In [147]:
col6else = str(list(Cashflow_analysis_else_df.columns))
index6else = colname6[Cashflow_analysis_else_df.columns]

In [148]:
index6else

F060201B           营业收入现金含量
F060301B          营业收入现金净含量
F060301C       营业收入现金净含量TTM
F060901B       筹资活动债权人现金净流量
F060901C    筹资活动债权人现金净流量TTM
F061001B        筹资活动股东现金净流量
F061301B             公司现金流1
F061302B             公司现金流2
F061302C          公司现金流TTM2
F061401B             股权现金流1
F061402B             股权现金流2
F061402C          股权现金流TTM2
F061501B        公司自由现金流(原有)
F061601B        股权自由现金流(原有)
F061701B            全部现金回收率
F061801B               营运指数
F062001B             现金适合比率
F062101B            现金再投资比率
F062201B           现金满足投资比率
Name: 0, dtype: object

In [156]:
with open('xjlfx_index.txt', 'a+', encoding='utf-8') as f:
    f.write("J66:" + "\n")
    f.write(col6j66 + "\n")
    for i in index6j66:
        f.write(i + '\n')
        
    f.write("ELSE:" + "\n")
    f.write(col6else + "\n")
    for i in index6else:
        f.write(i + '\n')
    f.close()

In [49]:
Cashflow_analysis_j66_df = data6j66.iloc[:,4:-1]
Cashflow_analysis_j66_df = delcol(Cashflow_analysis_j66_df)

In [53]:
Cashflow_analysis_j66_df = data6j66.iloc[:,4:-1]
Cashflow_analysis_j66_df = Cashflow_analysis_j66_df.apply(lambda x:x.astype(float))
Cashflow_analysis_j66_df.corr()

,F060101B,F060101C,F060301B,F060301C,F060401B,F060401C,F060901B,F060901C,F061001B,F061001C,F061302B,F061302C,F061402B,F061402C,F061701B,F061801B,F062001B,F062201B
F060101B,1.000000,0.671965,0.980096,0.664539,0.995646,0.663545,-0.140359,-0.091987,0.015867,-0.000551,0.276535,0.195611,0.227870,0.136620,0.856218,0.067788,0.449278,0.311166
F060101C,0.671965,1.000000,0.646079,0.984020,0.662290,0.995951,-0.106536,-0.089844,0.061098,0.082200,0.127456,0.202611,0.087787,0.131399,0.781401,0.093519,0.244425,0.510903
F060301B,0.980096,0.646079,1.000000,0.274184,0.933685,0.638924,-0.051899,-0.031670,-0.007149,-0.019206,0.133410,0.087781,0.116482,0.072152,0.418111,0.026568,0.473981,0.292778
F060301C,0.664539,0.984020,0.274184,1.000000,0.618322,0.979850,-0.109381,-0.093234,0.059955,0.079762,0.132904,0.208455,0.092205,0.138052,0.776748,0.085554,0.249556,0.518305
F060401B,0.995646,0.662290,0.933685,0.618322,1.000000,0.658132,-0.128294,-0.082216,0.011531,-0.004409,0.246747,0.172529,0.202038,0.121244,0.807085,0.085338,0.453283,0.293627
F060401C,0.663545,0.995951,0.638924,0.979850,0.658132,1.000000,-0.114663,-0.095415,0.062426,0.083040,0.123457,0.195311,0.080273,0.120230,0.767295,0.119149,0.241218,0.492307
F060901B,-0.140359,-0.106536,-0.051899,-0.109381,-0.128294,-0.114663,1.000000,0.629008,-0.333068,-0.267289,-0.283798,-0.294988,0.122468,0.167081,-0.090933,0.007196,-0.040751,-0.005936
F060901C,-0.091987,-0.089844,-0.031670,-0.093234,-0.082216,-0.095415,0.629008,1.000000,-0.207121,-0.255763,-0.168719,-0.254515,0.087168,0.151448,-0.079778,0.008538,-0.014163,-0.033358
F061001B,0.015867,0.061098,-0.007149,0.059955,0.011531,0.062426,-0.333068,-0.207121,1.000000,0.736781,-0.149090,-0.113086,-0.292937,-0.264144,-0.011173,-0.009619,0.013745,0.141186
F061001C,-0.000551,0.082200,-0.019206,0.079762,-0.004409,0.083040,-0.267289,-0.255763,0.736781,1.000000,-0.284641,-0.138295,-0.405859,-0.351830,0.010196,-0.013044,-0.042043,0.178790
F061302B,0.276535,0.127456,0.133410,0.132904,0.246747,0.123457,-0.283798,-0.168719,-0.149090,-0.284641,1.000000,0.700494,0.916910,0.618262,0.236606,0.004240,0.159463,-0.005447
F061302C,0.195611,0.202611,0.087781,0.208455,0.172529,0.195311,-0.294988,-0.254515,-0.113086,-0.138295,0.700494,1.000000,0.602864,0.839198,0.189692,0.000975,0.110993,0.032606
F061402B,0.227870,0.087787,0.116482,0.092205,0.202038,0.080273,0.122468,0.087168,-0.292937,-0.405859,0.916910,0.602864,1.000000,0.709555,0.207046,0.007383,0.148113,-0.008108
F061402C,0.136620,0.131399,0.072152,0.138052,0.121244,0.120230,0.167081,0.151448,-0.264144,-0.351830,0.618262,0.839198,0.709555,1.000000,0.139519,0.008079,0.106663,-0.005550
F061701B,0.856218,0.781401,0.418111,0.776748,0.807085,0.767295,-0.090933,-0.079778,-0.011173,0.010196,0.236606,0.189692,0.207046,0.139519,1.000000,0.084956,0.294291,0.395590
F061801B,0.067788,0.093519,0.026568,0.085554,0.085338,0.119149,0.007196,0.008538,-0.009619,-0.013044,0.004240,0.000975,0.007383,0.008079,0.084956,1.000000,0.010469,-0.005314
F062001B,0.449278,0.244425,0.473981,0.249556,0.453283,0.241218,-0.040751,-0.014163,0.013745,-0.042043,0.159463,0.110993,0.148113,0.106663,0.294291,0.010469,1.000000,0.095844
F062201B,0.311166,0.510903,0.292778,0.518305,0.293627,0.492307,-0.005936,-0.033358,0.141186,0.178790,-0.005447,0.032606,-0.008108,-0.005550,0.395590,-0.005314,0.095844,1.000000

In [90]:
col6j66 = str(list(Cashflow_analysis_j66_df.columns))
index6j66 = colname6[Cashflow_analysis_j66_df.columns]

In [91]:
index6j66

F060101B           净利润现金净含量
F060101C        净利润现金净含量TTM
F060901B       筹资活动债权人现金净流量
F060901C    筹资活动债权人现金净流量TTM
F061001B        筹资活动股东现金净流量
F061001C     筹资活动股东现金净流量TTM
F061302B             公司现金流2
F061302C          公司现金流TTM2
F061801B               营运指数
F062001B             现金适合比率
F062201B           现金满足投资比率
Name: 0, dtype: object

In [157]:
Cashflow_analysis_else_df = data6else.iloc[:,4:-1]
Cashflow_analysis_else_df = delcol(Cashflow_analysis_else_df)

20
20
经过筛选得到的相似的属性为：
 [('F061001B', 'F061001C')]

In [158]:
col6else = str(list(Cashflow_analysis_else_df.columns))
index6else = colname6[Cashflow_analysis_else_df.columns]

In [159]:
index6else

F060201B           营业收入现金含量
F060301B          营业收入现金净含量
F060301C       营业收入现金净含量TTM
F060901B       筹资活动债权人现金净流量
F060901C    筹资活动债权人现金净流量TTM
F061001B        筹资活动股东现金净流量
F061301B             公司现金流1
F061302B             公司现金流2
F061302C          公司现金流TTM2
F061401B             股权现金流1
F061402B             股权现金流2
F061402C          股权现金流TTM2
F061501B        公司自由现金流(原有)
F061601B        股权自由现金流(原有)
F061701B            全部现金回收率
F061801B               营运指数
F062001B             现金适合比率
F062101B            现金再投资比率
F062201B           现金满足投资比率
Name: 0, dtype: object

In [160]:
with open('xjlfx_index.txt', 'a+', encoding='utf-8') as f:
    f.write("J66:" + "\n")
    f.write(col6j66 + "\n")
    for i in index6j66:
        f.write(i + '\n')
        
    f.write("ELSE:" + "\n")
    f.write(col6else + "\n")
    for i in index6else:
        f.write(i + '\n')
    f.close()

## 7. Profitability

In [45]:
Profit_cap_j66_df = data7j66.iloc[:,4:-1]
Profit_cap_j66_df = delcol(Profit_cap_j66_df)

36
36
经过筛选得到的相似的属性为：
 [('F050101B', 'F050102B'), ('F050101B', 'F050103B'), ('F050101B', 'F050201B'), ('F050101B', 'F050202B'), ('F050101B', 'F050203B'), ('F050101B', 'F050401B'), ('F050101B', 'F050402B'), ('F050101B', 'F050403B'), ('F050101B', 'F050502B'), ('F050101B', 'F050503B'), ('F050102B', 'F050103B'), ('F050102B', 'F050104C'), ('F050102B', 'F050201B'), ('F050102B', 'F050202B'), ('F050102B', 'F050203B'), ('F050102B', 'F050204C'), ('F050102B', 'F050401B'), ('F050102B', 'F050402B'), ('F050102B', 'F050403B'), ('F050102B', 'F050404C'), ('F050102B', 'F050502B'), ('F050102B', 'F050503B'), ('F050103B', 'F050104C'), ('F050103B', 'F050201B'), ('F050103B', 'F050202B'), ('F050103B', 'F050203B'), ('F050103B', 'F050204C'), ('F050103B', 'F050401B'), ('F050103B', 'F050402B'), ('F050103B', 'F050403B'), ('F050103B', 'F050404C'), ('F050103B', 'F050502B'), ('F050103B', 'F050503B'), ('F050104C', 'F050202B'), ('F050104C', 'F050203B'), ('F050104C', 'F050204C'), ('F050104C', 'F050404C'), ('F050104C', 'F050504C'), ('F050104C', 'F051401C'), ('F050104C', 'F051501C'), ('F050201B', 'F050202B'), ('F050201B', 'F050203B'), ('F050201B', 'F050401B'), ('F050201B', 'F050402B'), ('F050201B', 'F050403B'), ('F050201B', 'F050502B'), ('F050201B', 'F050503B'), ('F050202B', 'F050203B'), ('F050202B', 'F050204C'), ('F050202B', 'F050401B'), ('F050202B', 'F050402B'), ('F050202B', 'F050403B'), ('F050202B', 'F050404C'), ('F050202B', 'F050502B'), ('F050202B', 'F050503B'), ('F050203B', 'F050204C'), ('F050203B', 'F050401B'), ('F050203B', 'F050402B'), ('F050203B', 'F050403B'), ('F050203B', 'F050404C'), ('F050203B', 'F050502B'), ('F050203B', 'F050503B'), ('F050204C', 'F050402B'), ('F050204C', 'F050403B'), ('F050204C', 'F050404C'), ('F050204C', 'F051501C'), ('F050401B', 'F050402B'), ('F050401B', 'F050403B'), ('F050401B', 'F050502B'), ('F050401B', 'F050503B'), ('F050402B', 'F050403B'), ('F050402B', 'F050404C'), ('F050402B', 'F050502B'), ('F050402B', 'F050503B'), ('F050403B', 'F050404C'), ('F050403B', 'F050502B'), ('F050403B', 'F050503B'), ('F050404C', 'F050504C'), ('F050404C', 'F051501C'), ('F050501B', 'F053001B'), ('F050501B', 'F053003B'), ('F050502B', 'F050503B'), ('F050504C', 'F051401B'), ('F050504C', 'F051401C'), ('F050504C', 'F051501B'), ('F050504C', 'F051501C'), ('F050504C', 'F051601B'), ('F051401B', 'F051401C'), ('F051401B', 'F051501B'), ('F051401B', 'F051501C'), ('F051401B', 'F051601B'), ('F051401C', 'F051501B'), ('F051401C', 'F051501C'), ('F051401C', 'F051601B'), ('F051501B', 'F051501C'), ('F051501B', 'F051601B'), ('F051501C', 'F051601B'), ('F051701B', 'F051701C'), ('F052201B', 'F052201C'), ('F053001B', 'F053002B'), ('F053001B', 'F053003B'), ('F053001B', 'F053101B'), ('F053001B', 'F053103B'), ('F053002B', 'F053003B'), ('F053003B', 'F053101B'), ('F053003B', 'F053103B'), ('F053101B', 'F053103B')]

In [46]:
col7j66 = str(list(Profit_cap_j66_df.columns))
index7j66 = colname7[Profit_cap_j66_df.columns]

In [47]:
index7j66

F050101B                  资产报酬率A
F050501B            净资产收益率（ROE）A
F050901B               净利润与利润总额比
F051601C               总营业成本率TTM
F051701B                   销售费用率
F052201B             资产减值损失／营业收入
F052901B                现金与利润总额比
F052901C             现金与利润总额比TTM
F053004C    归属于母公司净资产收益率（ROE）TTM
F053202B                   投资收益率
Name: 0, dtype: object

In [48]:
Profit_cap_j66_df.corr()

,F050101B,F050501B,F050901B,F051601C,F051701B,F052201B,F052901B,F052901C,F053004C,F053202B
F050101B,1.000000,0.159293,0.330125,-0.104924,0.002524,0.041645,0.013656,0.018373,0.102753,0.005854
F050501B,0.159293,1.000000,-0.087518,0.193429,0.046757,0.173508,0.092594,0.107634,0.471789,-0.028764
F050901B,0.330125,-0.087518,1.000000,-0.202645,-0.000883,-0.022694,-0.084715,-0.053489,0.112050,0.037018
F051601C,-0.104924,0.193429,-0.202645,1.000000,0.008900,0.431094,-0.012747,0.067892,0.220091,-0.032021
F051701B,0.002524,0.046757,-0.000883,0.008900,1.000000,-0.011044,-0.013089,0.008922,0.029707,-0.004698
F052201B,0.041645,0.173508,-0.022694,0.431094,-0.011044,1.000000,-0.058669,0.056161,0.099112,-0.047884
F052901B,0.013656,0.092594,-0.084715,-0.012747,-0.013089,-0.058669,1.000000,0.629868,0.062658,-0.022269
F052901C,0.018373,0.107634,-0.053489,0.067892,0.008922,0.056161,0.629868,1.000000,0.120970,-0.026514
F053004C,0.102753,0.471789,0.112050,0.220091,0.029707,0.099112,0.062658,0.120970,1.000000,-0.078856
F053202B,0.005854,-0.028764,0.037018,-0.032021,-0.004698,-0.047884,-0.022269,-0.026514,-0.078856,1.000000

In [164]:
Profit_cap_else_df = data7else.iloc[:,4:-1]
Profit_cap_else_df = delcol(Profit_cap_else_df)

32
32
经过筛选得到的相似的属性为：
 [('F050101B', 'F050201B'), ('F050101B', 'F050301B'), ('F050101B', 'F050403B'), ('F050101B', 'F051101B'), ('F050103B', 'F050203B'), ('F050201B', 'F050301B'), ('F050201B', 'F050403B'), ('F050201B', 'F051101B'), ('F050301B', 'F051101B'), ('F050403B', 'F051101B'), ('F050501B', 'F051201B'), ('F050501B', 'F053001B'), ('F050501B', 'F053101B'), ('F050601B', 'F050701B'), ('F050601B', 'F050801B'), ('F050701B', 'F050801B'), ('F051201B', 'F053001B'), ('F051201B', 'F053101B'), ('F053301B', 'F051301B'), ('F051401B', 'F051501B'), ('F051401B', 'F051601B'), ('F051401B', 'F052301B'), ('F051401B', 'F052401B'), ('F051501B', 'F051601B'), ('F051501B', 'F052301B'), ('F051501B', 'F052401B'), ('F051601B', 'F052301B'), ('F051601B', 'F052401B'), ('F051801B', 'F052001B'), ('F052301B', 'F052401B'), ('F053001B', 'F053101B'), ('F053003B', 'F053103B')]

In [165]:
col7else = str(list(Profit_cap_else_df.columns))
index7else = colname7[Profit_cap_else_df.columns]

In [166]:
index7else

F050101B                资产报酬率A
F050103B                资产报酬率C
F050303B             流动资产净利润率C
F050401B             固定资产净利润率A
F050501B          净资产收益率（ROE）A
F050503B          净资产收益率（ROE）C
F050601B           息税前利润（EBIT）
F053301B                 营业毛利率
F051401B                 营业利润率
F051701B                 销售费用率
F051801B                 管理费用率
F051901B                 财务费用率
F052101B               成本费用利润率
F052201B           资产减值损失／营业收入
F053003B    归属于母公司净资产收益率（ROE）C
Name: 0, dtype: object

In [167]:
with open('ylnl_index.txt', 'a+', encoding='utf-8') as f:
    f.write("J66:" + "\n")
    f.write(col7j66 + "\n")
    for i in index7j66:
        f.write(i + '\n')
        
    f.write("ELSE:" + "\n")
    f.write(col7else + "\n")
    for i in index7else:
        f.write(i + '\n')
    f.close()

In [ ]:
# data.to_excel(excel_writer = r"C:\Users\86180\Desktop\data8.xlsx")

# Outliers

In [ ]:
# ##读取离群值
# # 读取数据
# print("data is loading...")
# file = 'data8.xlsx'
# df1 = pd.read_excel(file)

In [ ]:
# df = df1.iloc[:,2:]
# df['label'] = 0

In [ ]:
# cnt = 0
# def detect_outliers(df,col):
#     q1 = df[col].quantile(0.25)
#     q3 = df[col].quantile(0.75)
#     iqr = q3-q1 #Interquartile range
#     fence_low  = q1-100*iqr
#     fence_high = q3+100*iqr
# #     df['label'] = df[col].apply(lambda x: 1 if x < fence_low)
#     df['label'][df[col]>fence_high] = 1
#     df['label'][df[col]<fence_low] = 1
#     cnt = df[df['label'] == 1]['label'].count()
#     return cnt

In [ ]:
# a = list(df)
# list_num = []
# for i in a[2:-4]:
#     list_num.append(detect_outliers(df,''+i+''))

In [ ]:
# list_num = list(np.diff(list_num))
# list_num.insert(0,55)
# len(list_num)